import jsPDF from "jspdf";
import type { PdfSections } from "@/components/results/ExportPdfModal";

interface DimensionRow {
  name: string;
  score: number;
  band: string;
  color: string;
  pastelColor: string;
  dimensionId: string;
}

interface FacetWithInterpretation {
  itemNumber: number;
  facetName: string;
  itemText: string;
  score: number;
  dimensionId: string;
  interpretation: {
    positive_self: string[];
    negative_self: string[];
    positive_others: string[];
    negative_others: string[];
  } | null;
}

interface AssessmentResponse {
  itemNumber: number;
  facetName: string;
  itemText: string;
  score: number;
  dimensionId: string;
}

export interface PdfData {
  userName: string;
  instrumentName: string;
  instrumentShortName: string;
  instrumentVersion: string;
  dateTaken: string;
  contextLabel: string;
  dimensions: DimensionRow[];
  statCards: { label: string; value: string }[];
  narrativeSections: {
    profile_overview?: string;
    dimension_highlights?: Record<string, string>;
    cross_assessment?: string;
    personal_summary?: string[];
    action_plan?: Array<{
      title: string;
      rationale: string;
      steps: string[];
      dimension_tags: string[];
    }>;
  } | null;
  elevatedFacets: FacetWithInterpretation[];
  suppressedFacets: FacetWithInterpretation[];
  assessmentResponses: AssessmentResponse[];
  recommendations: string[];
  isSliderInstrument: boolean;
  isPTP: boolean;
  fullFacetData: Array<{
    itemNumber: number;
    facetName: string;
    itemText: string;
    score: number;
    dimensionId: string;
    contextType: string | null;
  }>;
  ptpBrainOverviewVariant: "combined" | "professional" | "personal";
}

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN_L = 15;
const MARGIN_R = 15;
const MARGIN_T = 20;
const MARGIN_B = 25;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;
const FOOTER_Y = PAGE_H - 12;

// Standardized brand navy used for ALL primary text in this PDF.
const PRIMARY_TEXT_HEX = "#021F36";
const NAVY = [2, 31, 54] as const;
const MUTED = [109, 104, 117] as const;
const BLACK = [30, 30, 30] as const;
const SAND_BG = [249, 247, 241] as const;
const LIGHT_BG = [245, 247, 250] as const;
const GREEN = [34, 139, 34] as const;
const RED = [200, 50, 50] as const;
const ORANGE = [245, 116, 26] as const;
const DISCLAIMER_ICON_BG = [255, 230, 210] as const;

// Minimum vertical space (mm) required at the bottom of a page before
// starting a new paragraph or major heading block. If less than this is
// available, force a page break first to avoid widows/orphans.
const MIN_BLOCK_SPACE = 30;

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [parseInt(h.substring(0, 2), 16), parseInt(h.substring(2, 4), 16), parseInt(h.substring(4, 6), 16)];
}

function cleanMarkdown(text: string): string {
  return text.replace(/\*\*(.+?)\*\*/g, "$1").replace(/\*(.+?)\*/g, "$1");
}

function formatBand(band: string): string {
  return band.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function PTP_DIM_COLOR(dimId: string): string {
  const colors: Record<string, string> = {
    "DIM-PTP-01": PRIMARY_TEXT_HEX,
    "DIM-PTP-02": "#006D77",
    "DIM-PTP-03": "#6D6875",
    "DIM-PTP-04": "#3C096C",
    "DIM-PTP-05": "#2D6A4F",
  };
  return colors[dimId] ?? PRIMARY_TEXT_HEX;
}

export async function generateResultsPdf(data: PdfData, sections: PdfSections, options?: { returnBlob?: boolean }): Promise<void | Blob> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const { registerPdfFonts } = await import("./pdfFonts");
  registerPdfFonts(doc);
  let y = MARGIN_T;
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const addFooter = () => {
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated by BrainWise | ${today} | Confidential`, PAGE_W / 2, FOOTER_Y, { align: "center" });
    doc.setDrawColor(220, 220, 220);
    doc.line(MARGIN_L, FOOTER_Y - 3, PAGE_W - MARGIN_R, FOOTER_Y - 3);
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      y = MARGIN_T;
    }
  };

  // Ensure at least MIN_BLOCK_SPACE mm of room remains before starting a
  // paragraph or major heading block. Prevents single-line widows at the
  // bottom of a page.
  const ensureBlockSpace = (needed: number = MIN_BLOCK_SPACE) => {
    if (y + needed > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      y = MARGIN_T;
    }
  };

  const atTopOfPage = () => y <= MARGIN_T + 5;

  const sectionHeading = (title: string) => {
    ensureBlockSpace(MIN_BLOCK_SPACE);
    if (!atTopOfPage()) y += 4;
    doc.setFontSize(13);
    doc.setTextColor(...NAVY);
    doc.setFont("helvetica", "bold");
    doc.text(title, MARGIN_L, y);
    y += 2;
    doc.setDrawColor(...NAVY);
    doc.setLineWidth(0.5);
    doc.line(MARGIN_L, y, MARGIN_L + CONTENT_W, y);
    y += 6;
  };

  const bodyText = (text: string, indent = 0) => {
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...BLACK);
    const lines = doc.splitTextToSize(cleanMarkdown(text), CONTENT_W - indent);
    // Widow protection: if not enough room for at least 3 lines (~14mm),
    // jump to next page before starting the paragraph.
    if (lines.length > 1) ensureBlockSpace(Math.min(MIN_BLOCK_SPACE, lines.length * 4.5 + 4));
    for (const line of lines) {
      checkPageBreak(5);
      doc.text(line, MARGIN_L + indent, y);
      y += 4.5;
    }
  };

  // ── COVER PAGE ──
  // Fetch logo as base64 data URL so jsPDF can embed it
  const logoDataUrl = await (async () => {
    try {
      const res = await fetch("/logo-orange-white.png");
      if (!res.ok) return null;
      const blob = await res.blob();
      return await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    } catch {
      return null;
    }
  })();

  // Top half: navy block
  const NAVY_BLOCK_H = 150;
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, PAGE_W, NAVY_BLOCK_H, "F");

  // Logo (raster, fetched at runtime). If the fetch failed, fall back to text wordmark.
  if (logoDataUrl) {
    doc.addImage(logoDataUrl, "PNG", MARGIN_L, 18, 50, 0, undefined, "FAST");
  } else {
    doc.setFont("Poppins", "extrabold");
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.text("BrainWise Enterprises", MARGIN_L, 35);
  }

  // "ASSESSMENT REPORT" eyebrow
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(10);
  doc.setTextColor(...ORANGE);
  doc.setCharSpace(1.5);
  doc.text("ASSESSMENT REPORT", MARGIN_L, 72);
  doc.setCharSpace(0);

  // Headline "Personal Threat Profile™" — Poppins ExtraBold, white, large
  doc.setFont("Poppins", "extrabold");
  doc.setFontSize(36);
  doc.setTextColor(255, 255, 255);
  doc.text("Personal Threat", MARGIN_L, 88);
  doc.text("Profile", MARGIN_L, 105);
  const profileWidth = doc.getTextWidth("Profile");
  doc.setTextColor(...ORANGE);
  doc.setFontSize(20);
  doc.text("™", MARGIN_L + profileWidth + 1, 98);
  doc.setTextColor(255, 255, 255);

  // Description paragraph
  doc.setFont("Montserrat", "normal");
  doc.setFontSize(10);
  doc.setTextColor(220, 230, 240);
  const descText = "A neuroscience-based profile of how you respond to pressure, uncertainty, and change — mapped to the BrainWise 5P model.";
  const descLines = doc.splitTextToSize(descText, CONTENT_W - 60);
  doc.text(descLines, MARGIN_L, 120);

  // Context pill
  const contextLabel = (data.contextLabel || "Full").toUpperCase() + " CONTEXT";
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(9);
  const pillTextWidth = doc.getTextWidth(contextLabel);
  const pillW = pillTextWidth + 18;
  const pillH = 9;
  const pillY = 138;
  doc.setDrawColor(...ORANGE);
  doc.setLineWidth(0.5);
  doc.setFillColor(...NAVY);
  doc.roundedRect(MARGIN_L, pillY, pillW, pillH, pillH / 2, pillH / 2, "FD");
  doc.setFillColor(...ORANGE);
  doc.circle(MARGIN_L + 5, pillY + pillH / 2, 1.3, "F");
  doc.setTextColor(...ORANGE);
  doc.text(contextLabel, MARGIN_L + 10, pillY + pillH / 2 + 1.2);

  // Bottom half: sand background
  doc.setFillColor(...SAND_BG);
  doc.rect(0, NAVY_BLOCK_H, PAGE_W, PAGE_H - NAVY_BLOCK_H, "F");

  // Field row 1: Participant + Date Completed
  const fieldY = NAVY_BLOCK_H + 14;
  const fieldColW = (CONTENT_W - 10) / 2;

  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(8);
  doc.setTextColor(...ORANGE);
  doc.setCharSpace(1);
  doc.text("PARTICIPANT", MARGIN_L, fieldY);
  doc.text("DATE COMPLETED", MARGIN_L + fieldColW + 10, fieldY);
  doc.setCharSpace(0);

  doc.setFont("Poppins", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...NAVY);
  doc.text(data.userName, MARGIN_L, fieldY + 9);
  doc.text(data.dateTaken, MARGIN_L + fieldColW + 10, fieldY + 9);

  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_L, fieldY + 13, MARGIN_L + fieldColW, fieldY + 13);
  doc.line(MARGIN_L + fieldColW + 10, fieldY + 13, MARGIN_L + CONTENT_W, fieldY + 13);

  // Field row 2: Instrument Version
  const versionY = fieldY + 28;
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(8);
  doc.setTextColor(...ORANGE);
  doc.setCharSpace(1);
  doc.text("INSTRUMENT VERSION", MARGIN_L, versionY);
  doc.setCharSpace(0);

  doc.setFont("Poppins", "normal");
  doc.setFontSize(13);
  doc.setTextColor(...NAVY);
  doc.text(data.instrumentVersion, MARGIN_L, versionY + 9);
  doc.line(MARGIN_L, versionY + 13, MARGIN_L + CONTENT_W, versionY + 13);

  // Disclaimer card
  const disclaimerY = versionY + 28;
  const disclaimerText = "This report is generated by an AI model and is intended for personal reflection only. It does not constitute a clinical diagnosis or professional psychological advice. Results should be interpreted in conjunction with qualified professional guidance.";
  doc.setFont("Montserrat", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...BLACK);
  const disclaimerLines = doc.splitTextToSize(disclaimerText, CONTENT_W - 20);
  const disclaimerH = disclaimerLines.length * 4.5 + 18;

  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(225, 220, 210);
  doc.setLineWidth(0.3);
  doc.roundedRect(MARGIN_L, disclaimerY, CONTENT_W, disclaimerH, 3, 3, "FD");

  doc.setFillColor(...DISCLAIMER_ICON_BG);
  doc.circle(MARGIN_L + 9, disclaimerY + 9, 4, "F");
  doc.setFont("Poppins", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...ORANGE);
  doc.text("i", MARGIN_L + 9, disclaimerY + 10.5, { align: "center" });

  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(9);
  doc.setTextColor(...NAVY);
  doc.setCharSpace(0.5);
  doc.text("IMPORTANT — PLEASE READ", MARGIN_L + 16, disclaimerY + 10);
  doc.setCharSpace(0);

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(60, 60, 60);
  doc.text(disclaimerLines, MARGIN_L + 6, disclaimerY + 18);

  // Footer
  const footerCoverY = PAGE_H - 22;
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(8);
  doc.setTextColor(...NAVY);
  doc.setCharSpace(0.8);
  doc.text("GENERATED BY BRAINWISE ENTERPRISES, LLC", MARGIN_L, footerCoverY);
  doc.setCharSpace(0);

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  const dateRight = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }).toUpperCase();
  doc.text(dateRight, PAGE_W - MARGIN_R, footerCoverY, { align: "right" });

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(7);
  doc.setTextColor(140, 140, 140);
  const copyText = `© ${new Date().getFullYear()} BrainWise Enterprises. Confidential and proprietary. Shared with the named recipient for evaluation only; not to be reproduced or disclosed without written consent. The Personal Threat Profile™ and 5P model are the property of BrainWise Enterprises.`;
  const copyLines = doc.splitTextToSize(copyText, CONTENT_W);
  doc.text(copyLines, MARGIN_L, footerCoverY + 5);

  doc.addPage();
  y = MARGIN_T;

  // ── PROFILE OVERVIEW ──
  if (sections.profileOverview) {
    sectionHeading("Profile Overview");

    const cardW = (CONTENT_W - 6) / 3;
    data.statCards.forEach((card, i) => {
      const x = MARGIN_L + i * (cardW + 3);
      doc.setFillColor(...LIGHT_BG);
      doc.roundedRect(x, y, cardW, 14, 1.5, 1.5, "F");
      doc.setFontSize(7);
      doc.setTextColor(...MUTED);
      doc.text(card.label, x + 3, y + 5);
      doc.setFontSize(9);
      doc.setTextColor(...BLACK);
      doc.setFont("helvetica", "bold");
      const truncVal = card.value.length > 22 ? card.value.slice(0, 20) + "…" : card.value;
      doc.text(truncVal, x + 3, y + 11);
      doc.setFont("helvetica", "normal");
    });
    y += 20;

    if (data.isPTP && data.dimensions.length > 0) {
      checkPageBreak(40);
      const dimCardW = (CONTENT_W - (data.dimensions.length - 1) * 3) / data.dimensions.length;
      data.dimensions.forEach((dim, i) => {
        const x = MARGIN_L + i * (dimCardW + 3);
        const rgb = hexToRgb(dim.color);
        const pastelRgb = hexToRgb(dim.pastelColor);
        doc.setFillColor(pastelRgb[0], pastelRgb[1], pastelRgb[2]);
        doc.roundedRect(x, y, dimCardW, 30, 2, 2, "F");
        doc.setFillColor(rgb[0], rgb[1], rgb[2]);
        doc.circle(x + dimCardW / 2, y + 5, 2, "F");
        doc.setFontSize(7);
        doc.setTextColor(...BLACK);
        doc.setFont("helvetica", "bold");
        const nameLines = doc.splitTextToSize(dim.name, dimCardW - 4);
        doc.text(nameLines[0], x + dimCardW / 2, y + 11, { align: "center" });
        if (nameLines[1]) doc.text(nameLines[1], x + dimCardW / 2, y + 15, { align: "center" });
        doc.setFontSize(14);
        doc.setTextColor(rgb[0], rgb[1], rgb[2]);
        doc.setFont("helvetica", "bold");
        doc.text(String(dim.score), x + dimCardW / 2, y + 23, { align: "center" });
        doc.setFontSize(6.5);
        doc.setTextColor(...MUTED);
        doc.setFont("helvetica", "normal");
        doc.text(formatBand(dim.band), x + dimCardW / 2, y + 28, { align: "center" });
      });
      y += 36;
    }
  }

  // ── DRIVING FACET SCORES ──
  if (sections.drivingFacetScores && (data.elevatedFacets.length > 0 || data.suppressedFacets.length > 0)) {
    sectionHeading("Driving Facet Scores");

    const renderFacetScoreTable = (title: string, facets: FacetWithInterpretation[]) => {
      checkPageBreak(12 + facets.length * 7);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...BLACK);
      doc.text(title, MARGIN_L, y);
      y += 5;
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.text("Facet", MARGIN_L, y);
      doc.text("Score", MARGIN_L + CONTENT_W * 0.82, y);
      y += 2;
      doc.setDrawColor(200, 200, 200);
      doc.line(MARGIN_L, y, MARGIN_L + CONTENT_W, y);
      y += 4;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      for (let i = 0; i < facets.length; i++) {
        checkPageBreak(7);
        const f = facets[i];
        if (i % 2 === 0) {
          doc.setFillColor(250, 250, 252);
          doc.rect(MARGIN_L, y - 3, CONTENT_W, 6, "F");
        }
        const rgb = hexToRgb(PTP_DIM_COLOR(f.dimensionId));
        doc.setFillColor(rgb[0], rgb[1], rgb[2]);
        doc.circle(MARGIN_L + 2, y - 1, 1.5, "F");
        const truncText = f.itemText.length > 85 ? f.itemText.slice(0, 82) + "…" : f.itemText;
        doc.setTextColor(...BLACK);
        doc.text(truncText, MARGIN_L + 6, y);
        doc.text(String(f.score), MARGIN_L + CONTENT_W * 0.82, y);
        y += 6;
      }
      y += 6;
    };

    if (data.elevatedFacets.length > 0) renderFacetScoreTable("Elevated Facets", data.elevatedFacets);
    if (data.suppressedFacets.length > 0) renderFacetScoreTable("Suppressed Facets", data.suppressedFacets);
    addFooter();
    doc.addPage();
    y = MARGIN_T;
  }

  // ── PROFILE OVERVIEW NARRATIVE ──
  if (sections.profileOverviewNarrative && data.narrativeSections?.profile_overview) {
    sectionHeading("Profile Overview Narrative");
    bodyText(data.narrativeSections.profile_overview);
    y += 4;
  }

  // ── PTP AND BRAIN OVERVIEW ──
  if (sections.ptpBrainOverview) {
    sectionHeading("PTP and Brain Overview");
    const overviewText = "Content coming soon. This section will provide a brief introduction to the Personal Threat Profile framework and its neuroscientific basis, including links to supporting resources and a video overview.";
    const overviewLines = doc.splitTextToSize(overviewText, CONTENT_W - 12);
    const overviewH = overviewLines.length * 4.5 + 8;
    checkPageBreak(overviewH + 4);
    doc.setFillColor(...SAND_BG);
    doc.rect(MARGIN_L + 1.5, y, CONTENT_W - 1.5, overviewH, "F");
    doc.setFillColor(...NAVY);
    doc.rect(MARGIN_L, y, 1.5, overviewH, "F");
    doc.setFontSize(8.5);
    doc.setTextColor(...BLACK);
    doc.text(overviewLines, MARGIN_L + 6, y + 5);
    y += overviewH + 6;
    addFooter();
    doc.addPage();
    y = MARGIN_T;
  }

  // ── DIMENSION HIGHLIGHTS ──
  if (sections.dimensionHighlights && data.narrativeSections?.dimension_highlights) {
    sectionHeading("Dimension Highlights");
    for (const dim of data.dimensions) {
      const text = data.narrativeSections.dimension_highlights[dim.dimensionId];
      if (!text) continue;
      const rgb = hexToRgb(dim.color);
      const pastelRgb = hexToRgb(dim.pastelColor);
      const textLines = doc.splitTextToSize(cleanMarkdown(text), CONTENT_W - 12);
      const cardH = textLines.length * 4.5 + 14;
      checkPageBreak(cardH + 4);
      doc.setFillColor(pastelRgb[0], pastelRgb[1], pastelRgb[2]);
      doc.roundedRect(MARGIN_L, y, CONTENT_W, cardH, 2, 2, "F");
      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.rect(MARGIN_L, y, 1.5, cardH, "F");
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...BLACK);
      doc.text(`${dim.name} — ${dim.score}`, MARGIN_L + 6, y + 7);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...MUTED);
      doc.text(textLines, MARGIN_L + 6, y + 13);
      y += cardH + 4;
    }
    y += 2;
  }

  // ── DRIVING FACET INSIGHTS ──
  if (sections.drivingFacetInsights && (data.elevatedFacets.length > 0 || data.suppressedFacets.length > 0)) {
    addFooter();
    doc.addPage();
    y = MARGIN_T;
    sectionHeading("Driving Facet Insights");

    const renderFacetInsights = (title: string, facets: FacetWithInterpretation[]) => {
      if (!facets.length) return;
      checkPageBreak(40);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...NAVY);
      doc.text(title, MARGIN_L, y);
      y += 7;

      for (const f of facets) {
        if (!f.interpretation) continue;
        const rgb = hexToRgb(PTP_DIM_COLOR(f.dimensionId));

        // Estimate total height of this facet block before rendering
        const qLinesEst = doc.splitTextToSize(f.itemText, CONTENT_W - 20);
        const selfItemsEst = [
          ...(f.interpretation?.positive_self ?? []),
          ...(f.interpretation?.negative_self ?? []),
        ];
        const othersItemsEst = [
          ...(f.interpretation?.positive_others ?? []),
          ...(f.interpretation?.negative_others ?? []),
        ];
        const impactRowsEst = Math.max(selfItemsEst.length, othersItemsEst.length);
        const estimatedBlockH = 15 + 5 + impactRowsEst * 12 + 6;
        ensureBlockSpace(Math.max(MIN_BLOCK_SPACE, Math.min(estimatedBlockH, 80)));
        doc.setFillColor(rgb[0], rgb[1], rgb[2]);
        doc.rect(MARGIN_L, y, 1.5, 12, "F");
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...BLACK);
        doc.text(f.facetName, MARGIN_L + 5, y + 5);
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...MUTED);
        const qLines = doc.splitTextToSize(f.itemText, CONTENT_W - 20);
        doc.text(qLines[0] ?? "", MARGIN_L + 5, y + 10);
        doc.setFillColor(rgb[0], rgb[1], rgb[2]);
        doc.roundedRect(MARGIN_L + CONTENT_W - 12, y + 2, 12, 8, 1, 1, "F");
        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(255, 255, 255);
        doc.text(String(f.score), MARGIN_L + CONTENT_W - 6, y + 7, { align: "center" });
        y += 15;

        const colW = (CONTENT_W - 4) / 2;

        // Estimate total height of all impact rows for this facet
        const selfItemsAll = [
          ...f.interpretation.positive_self.map(t => t),
          ...f.interpretation.negative_self.map(t => t),
        ];
        const othersItemsAll = [
          ...f.interpretation.positive_others.map(t => t),
          ...f.interpretation.negative_others.map(t => t),
        ];
        const maxRowsAll = Math.max(selfItemsAll.length, othersItemsAll.length);
        const estimatedImpactH = 5 + maxRowsAll * 14;
        checkPageBreak(estimatedImpactH);

        doc.setFontSize(7.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...NAVY);
        doc.text("Impact on self", MARGIN_L, y);
        doc.text("Impact on others", MARGIN_L + colW + 4, y);
        y += 5;

        const selfItems = [
          ...f.interpretation.positive_self.map((t) => ({ text: t, positive: true })),
          ...f.interpretation.negative_self.map((t) => ({ text: t, positive: false })),
        ];
        const othersItems = [
          ...f.interpretation.positive_others.map((t) => ({ text: t, positive: true })),
          ...f.interpretation.negative_others.map((t) => ({ text: t, positive: false })),
        ];
        const maxItems = Math.max(selfItems.length, othersItems.length);

        for (let i = 0; i < maxItems; i++) {
          const selfItem = selfItems[i];
          const othersItem = othersItems[i];
          const selfLines = selfItem ? doc.splitTextToSize(cleanMarkdown(selfItem.text), colW - 6) : [];
          const othersLines = othersItem ? doc.splitTextToSize(cleanMarkdown(othersItem.text), colW - 6) : [];
          const rowH = Math.max(selfLines.length, othersLines.length) * 4 + 3;
          checkPageBreak(rowH + 2);

          if (selfItem) {
            doc.setFontSize(8);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(selfItem.positive ? GREEN[0] : RED[0], selfItem.positive ? GREEN[1] : RED[1], selfItem.positive ? GREEN[2] : RED[2]);
            doc.text(selfItem.positive ? "+" : "-", MARGIN_L, y + 3);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(...BLACK);
            doc.text(selfLines, MARGIN_L + 5, y + 3);
          }

          if (othersItem) {
            doc.setFontSize(8);
            doc.setFont("helvetica", "bold");
            doc.setTextColor(othersItem.positive ? GREEN[0] : RED[0], othersItem.positive ? GREEN[1] : RED[1], othersItem.positive ? GREEN[2] : RED[2]);
            doc.text(othersItem.positive ? "+" : "-", MARGIN_L + colW + 4, y + 3);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(...BLACK);
            doc.text(othersLines, MARGIN_L + colW + 9, y + 3);
          }

          y += rowH;
        }
        y += 6;
      }
    };

    renderFacetInsights("Elevated Facets", data.elevatedFacets);
    renderFacetInsights("Suppressed Facets", data.suppressedFacets);
  }

  // ── CROSS-ASSESSMENT CONNECTIONS ──
  if (sections.crossAssessmentConnections && data.narrativeSections?.cross_assessment) {
    addFooter();
    doc.addPage();
    y = MARGIN_T;
    sectionHeading("Cross-Assessment Connections");
    bodyText(data.narrativeSections.cross_assessment);
    y += 4;
  }

  // ── ASSESSMENT RESPONSES ──
  if (sections.assessmentResponses && data.assessmentResponses.length > 0) {
    sectionHeading("Assessment Responses");
    const contextNote = data.contextLabel
      ? `${data.assessmentResponses.length} responses — ${data.contextLabel} context`
      : `${data.assessmentResponses.length} responses`;
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(contextNote, MARGIN_L, y);
    y += 6;

    for (const r of data.assessmentResponses) {
      const rgb = hexToRgb(PTP_DIM_COLOR(r.dimensionId));
      const labelText = `Q${r.itemNumber} — ${r.facetName}`;
      const questionLines = doc.splitTextToSize(r.itemText, CONTENT_W - 20);
      const rowH = questionLines.length * 4 + 8;
      checkPageBreak(rowH + 2);

      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.rect(MARGIN_L, y, 1.5, rowH, "F");

      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...BLACK);
      doc.text(labelText, MARGIN_L + 5, y + 5);

      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...MUTED);
      doc.text(questionLines, MARGIN_L + 5, y + 10);

      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.roundedRect(MARGIN_L + CONTENT_W - 12, y + rowH / 2 - 4, 12, 8, 1, 1, "F");
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text(String(r.score), MARGIN_L + CONTENT_W - 6, y + rowH / 2 + 1, { align: "center" });

      doc.setDrawColor(230, 230, 230);
      doc.line(MARGIN_L, y + rowH, MARGIN_L + CONTENT_W, y + rowH);
      y += rowH + 1;
    }
  }

  addFooter();

  // Stamp "Page X of Y" on every content page (skip the cover at page 1).
  const totalPages = doc.getNumberOfPages();
  const contentTotalPages = totalPages - 1;
  for (let p = 2; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(`Page ${p - 1} of ${contentTotalPages}`, PAGE_W - MARGIN_R, FOOTER_Y, { align: "right" });
  }

  const lastName = data.userName.split(" ").pop() || "User";
  const dateStr = new Date().toISOString().slice(0, 10);
  const contextSuffix = data.contextLabel ? `-${data.contextLabel}` : "";
  if (options?.returnBlob) {
    return doc.output("blob");
  }
  doc.save(`BrainWise-${data.instrumentShortName}${contextSuffix}-${lastName}-${dateStr}.pdf`);
}
