import jsPDF from "jspdf";

export interface NaiPdfSections {
  profileOverview: boolean;
  profileOverviewNarrative: boolean;
  naiOverview: boolean;
  dimensionHighlights: boolean;
  patternAlert: boolean;
  individualResponses: boolean;
  cafesPtpMapping: boolean;
  crossAssessmentInterpretation: boolean;
  assessmentResponses: boolean;
}

interface NaiDimensionRow {
  dimensionId: string;
  name: string;
  score: number;
  band: string;
  color: string;
  pastelColor: string;
}

interface NaiOutlier {
  itemNumber: number;
  facetName: string;
  itemText: string;
  score: number;
  dimensionId: string;
  dimensionName: string;
  interpretation: string | null;
  relatedPtpFacets: string | null;
}

interface NaiResponse {
  itemNumber: number;
  facetName: string;
  itemText: string;
  score: number | null;
  dimensionId: string;
  hasResponse: boolean;
}

interface NaiCafesMappingRow {
  dimensionId: string;
  dimensionName: string;
  score: number;
  band: string;
  color: string;
  pastelColor: string;
  primaryPtpDomain: string;
  secondaryPtpDomain: string;
  ptpFacets: Array<{ name: string; refs: string }>;
  coachingQuestions: string[];
}

export interface NaiPdfData {
  userName: string;
  instrumentName: string;
  instrumentShortName: string;
  instrumentVersion: string;
  dateTaken: string;
  isCoachView: boolean;
  statCards: { label: string; value: string }[];
  dimensions: NaiDimensionRow[];
  profileOverviewText: string | null;
  dimensionHighlights: Array<{ dimensionId: string; name: string; score: number; band: string; color: string; pastelColor: string; highlight: string | null; areasOfFocus: string | null }>;
  patternAlert: { body: string; suggestions: string[] } | null;
  outlierItems: NaiOutlier[];
  cafesPtpMapping: NaiCafesMappingRow[];
  crossAssessment: { interpretation: string; suggestions: string[] } | null;
  assessmentResponses: NaiResponse[];
}

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN_L = 15;
const MARGIN_R = 15;
const MARGIN_T = 20;
const MARGIN_B = 25;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;
const FOOTER_Y = PAGE_H - 12;

// Standardized brand navy used for ALL primary text in this PDF.
const PRIMARY_TEXT_HEX = "#021F36";
const NAVY = [2, 31, 54] as const;
const MUTED = [109, 104, 117] as const;
const BLACK = [30, 30, 30] as const;
const SAND_BG = [249, 247, 241] as const;
const LIGHT_BG = [245, 247, 250] as const;

// Minimum vertical space (mm) required at the bottom of a page before
// starting a new paragraph or major heading block. If less than this is
// available, force a page break first to avoid widows/orphans.
const MIN_BLOCK_SPACE = 30;

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [parseInt(h.substring(0, 2), 16), parseInt(h.substring(2, 4), 16), parseInt(h.substring(4, 6), 16)];
}

function cleanMarkdown(text: string): string {
  return text.replace(/\*\*(.+?)\*\*/g, "$1").replace(/\*(.+?)\*/g, "$1");
}

export function generateNaiPdf(data: NaiPdfData, sections: NaiPdfSections, options?: { returnBlob?: boolean }): void | Blob {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN_T;
  const today = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const addFooter = () => {
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(`Generated by BrainWise | ${today} | Confidential`, PAGE_W / 2, FOOTER_Y, { align: "center" });
    doc.setDrawColor(220, 220, 220);
    doc.line(MARGIN_L, FOOTER_Y - 3, PAGE_W - MARGIN_R, FOOTER_Y - 3);
  };

  let currentSectionTitle: string | null = null;

  const renderContinuationHeader = () => {
    if (!currentSectionTitle) return;
    doc.setFontSize(10);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "italic");
    doc.text(`${currentSectionTitle} (cont.)`, MARGIN_L, y);
    y += 2;
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(0.3);
    doc.line(MARGIN_L, y, MARGIN_L + CONTENT_W, y);
    y += 5;
    doc.setFont("helvetica", "normal");
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      y = MARGIN_T;
      if (currentSectionTitle) renderContinuationHeader();
    }
  };

  // Ensure at least MIN_BLOCK_SPACE mm of room remains before starting a
  // paragraph or major heading block. Prevents single-line widows at the
  // bottom of a page.
  const ensureBlockSpace = (needed: number = MIN_BLOCK_SPACE) => {
    if (y + needed > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      y = MARGIN_T;
      if (currentSectionTitle) renderContinuationHeader();
    }
  };

  const atTopOfPage = () => y <= MARGIN_T + 5;

  const sectionHeading = (title: string, minContentNeeded = 50) => {
    // Clear previous section title BEFORE the page-break check so we don't
    // render the previous section's continuation header on a new page.
    currentSectionTitle = null;
    // Require enough room for heading + at least the start of first content card.
    ensureBlockSpace(Math.max(MIN_BLOCK_SPACE, 15 + minContentNeeded));
    currentSectionTitle = title;
    if (!atTopOfPage()) y += 4;
    doc.setFontSize(13);
    doc.setTextColor(...NAVY);
    doc.setFont("helvetica", "bold");
    doc.text(title, MARGIN_L, y);
    y += 2;
    doc.setDrawColor(...NAVY);
    doc.setLineWidth(0.5);
    doc.line(MARGIN_L, y, MARGIN_L + CONTENT_W, y);
    y += 6;
  };

  const bodyText = (text: string, indent = 0) => {
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...BLACK);
    const lines = doc.splitTextToSize(cleanMarkdown(text), CONTENT_W - indent);
    // Widow protection.
    if (lines.length > 1) ensureBlockSpace(Math.min(MIN_BLOCK_SPACE, lines.length * 4.5 + 4));
    for (const line of lines) {
      checkPageBreak(5);
      doc.text(line, MARGIN_L + indent, y);
      y += 4.5;
    }
  };

  // ── COVER PAGE ──
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, PAGE_W, 80, "F");

  doc.setFontSize(28);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("BrainWise", MARGIN_L, 35);

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(data.instrumentName, MARGIN_L, 48);

  if (data.isCoachView) {
    doc.setFontSize(11);
    doc.setTextColor(200, 220, 235);
    doc.text("Coach Report", MARGIN_L, 58);
  }

  const coverY = 110;
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text("Participant", MARGIN_L, coverY);
  doc.setFontSize(12);
  doc.setTextColor(...BLACK);
  doc.setFont("helvetica", "bold");
  doc.text(data.userName, MARGIN_L, coverY + 7);

  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.text("Date Completed", MARGIN_L, coverY + 20);
  doc.setFontSize(11);
  doc.setTextColor(...BLACK);
  doc.text(data.dateTaken, MARGIN_L, coverY + 27);

  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text("Version", MARGIN_L, coverY + 40);
  doc.setFontSize(11);
  doc.setTextColor(...BLACK);
  doc.text(data.instrumentVersion, MARGIN_L, coverY + 47);

  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text("Cover page design pending final branding guidelines.", MARGIN_L, PAGE_H - 20);

  const disclaimerTextCover = "This report is generated by an AI model and is intended for personal reflection only. It does not constitute clinical diagnosis or professional psychological advice. Results should be interpreted in conjunction with qualified professional guidance.";
  const disclaimerLinesCover = doc.splitTextToSize(disclaimerTextCover, CONTENT_W - 8);
  const disclaimerHCover = disclaimerLinesCover.length * 3.8 + 6;
  const disclaimerYCover = PAGE_H - 50;
  doc.setFillColor(...SAND_BG);
  doc.roundedRect(MARGIN_L, disclaimerYCover, CONTENT_W, disclaimerHCover, 2, 2, "F");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(disclaimerLinesCover, MARGIN_L + 4, disclaimerYCover + 5);

  addFooter();
  doc.addPage();
  y = MARGIN_T;

  // ── PROFILE OVERVIEW ──
  if (sections.profileOverview) {
    sectionHeading("Profile Overview");

    const cardW = (CONTENT_W - 6) / 3;
    data.statCards.forEach((card, i) => {
      const x = MARGIN_L + i * (cardW + 3);
      doc.setFillColor(...LIGHT_BG);
      doc.roundedRect(x, y, cardW, 14, 1.5, 1.5, "F");
      doc.setFontSize(7);
      doc.setTextColor(...MUTED);
      doc.text(card.label, x + 3, y + 5);
      doc.setFontSize(9);
      doc.setTextColor(...BLACK);
      doc.setFont("helvetica", "bold");
      const truncVal = card.value.length > 22 ? card.value.slice(0, 20) + "…" : card.value;
      doc.text(truncVal, x + 3, y + 11);
      doc.setFont("helvetica", "normal");
    });
    y += 20;

    if (data.dimensions.length > 0) {
      checkPageBreak(40);
      const dimCardW = (CONTENT_W - (data.dimensions.length - 1) * 3) / data.dimensions.length;
      data.dimensions.forEach((dim, i) => {
        const x = MARGIN_L + i * (dimCardW + 3);
        const rgb = hexToRgb(dim.color);
        const pastelRgb = hexToRgb(dim.pastelColor);
        doc.setFillColor(pastelRgb[0], pastelRgb[1], pastelRgb[2]);
        doc.roundedRect(x, y, dimCardW, 30, 2, 2, "F");
        doc.setFillColor(rgb[0], rgb[1], rgb[2]);
        doc.circle(x + dimCardW / 2, y + 5, 2, "F");
        doc.setFontSize(7);
        doc.setTextColor(...BLACK);
        doc.setFont("helvetica", "bold");
        const nameLines = doc.splitTextToSize(dim.name, dimCardW - 4);
        doc.text(nameLines[0], x + dimCardW / 2, y + 11, { align: "center" });
        if (nameLines[1]) doc.text(nameLines[1], x + dimCardW / 2, y + 15, { align: "center" });
        doc.setFontSize(14);
        doc.setTextColor(rgb[0], rgb[1], rgb[2]);
        doc.setFont("helvetica", "bold");
        doc.text(String(dim.score), x + dimCardW / 2, y + 23, { align: "center" });
        doc.setFontSize(6.5);
        doc.setTextColor(...MUTED);
        doc.setFont("helvetica", "normal");
        doc.text(dim.band, x + dimCardW / 2, y + 28, { align: "center" });
      });
      y += 36;
    }
  }

  // ── PROFILE OVERVIEW NARRATIVE ──
  if (sections.profileOverviewNarrative && data.profileOverviewText) {
    sectionHeading("Profile Overview Narrative");
    bodyText(data.profileOverviewText);
    y += 4;
  }

  // ── NAI OVERVIEW ──
  if (sections.naiOverview) {
    sectionHeading("NAI Overview");
    const overviewText = "Content coming soon. This section will provide a brief introduction to the Neuroscience Adoption Index framework, its neuroscientific basis, and how the five C.A.F.E.S. dimensions connect to the brain's protection system.";
    const overviewLines = doc.splitTextToSize(overviewText, CONTENT_W - 12);
    const overviewH = overviewLines.length * 4.5 + 8;
    checkPageBreak(overviewH + 4);
    doc.setFillColor(...SAND_BG);
    doc.rect(MARGIN_L + 1.5, y, CONTENT_W - 1.5, overviewH, "F");
    doc.setFillColor(...NAVY);
    doc.rect(MARGIN_L, y, 1.5, overviewH, "F");
    doc.setFontSize(8.5);
    doc.setTextColor(...BLACK);
    doc.text(overviewLines, MARGIN_L + 6, y + 5);
    y += overviewH + 6;
  }

  // ── DIMENSION HIGHLIGHTS ──
  if (sections.dimensionHighlights && data.dimensionHighlights.length > 0) {
    sectionHeading("Dimension Highlights", 55);
    for (const dim of data.dimensionHighlights) {
      const rgb = hexToRgb(dim.color);
      const pastelRgb = hexToRgb(dim.pastelColor);
      const highlightLines = dim.highlight ? doc.splitTextToSize(cleanMarkdown(dim.highlight), CONTENT_W - 12) : [];
      const focusLines = dim.areasOfFocus ? doc.splitTextToSize(cleanMarkdown(dim.areasOfFocus), CONTENT_W - 12) : [];
      const focusLabelH = dim.areasOfFocus ? 5 : 0;
      const cardH = 10 + highlightLines.length * 4.5 + focusLabelH + focusLines.length * 4.5 + 6;
      checkPageBreak(cardH + 4);
      doc.setFillColor(pastelRgb[0], pastelRgb[1], pastelRgb[2]);
      doc.roundedRect(MARGIN_L, y, CONTENT_W, cardH, 2, 2, "F");
      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.rect(MARGIN_L, y, 1.5, cardH, "F");
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(rgb[0], rgb[1], rgb[2]);
      doc.text(`${dim.name} — ${dim.score}  (${dim.band})`, MARGIN_L + 6, y + 7);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...BLACK);
      let cursor = y + 13;
      if (highlightLines.length > 0) {
        doc.text(highlightLines, MARGIN_L + 6, cursor);
        cursor += highlightLines.length * 4.5;
      }
      if (dim.areasOfFocus) {
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(rgb[0], rgb[1], rgb[2]);
        doc.text("AREAS OF FOCUS", MARGIN_L + 6, cursor + 3);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...MUTED);
        doc.text(focusLines, MARGIN_L + 6, cursor + 8);
      }
      y += cardH + 4;
    }
    y += 2;
  }

  // ── PATTERN ALERT (coach only) ──
  if (sections.patternAlert && data.patternAlert) {
    sectionHeading("Pattern Alert");
    const bodyLines = doc.splitTextToSize(cleanMarkdown(data.patternAlert.body), CONTENT_W - 12);
    const suggestionBlocks = data.patternAlert.suggestions.map((s, i) => {
      return doc.splitTextToSize(`${i + 1}. ${cleanMarkdown(s)}`, CONTENT_W - 12);
    });
    const suggestionsH = suggestionBlocks.reduce((acc, block) => acc + block.length * 4.5, 0);
    const cardH = 10 + bodyLines.length * 4.5 + 4 + suggestionsH + 6;
    checkPageBreak(cardH + 4);
    doc.setFillColor(...SAND_BG);
    doc.rect(MARGIN_L + 1.5, y, CONTENT_W - 1.5, cardH, "F");
    doc.setFillColor(...NAVY);
    doc.rect(MARGIN_L, y, 1.5, cardH, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text("Pattern alert — broad Protection activation", MARGIN_L + 6, y + 7);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...BLACK);
    doc.text(bodyLines, MARGIN_L + 6, y + 13);
    let cursor = y + 13 + bodyLines.length * 4.5 + 3;
    for (const block of suggestionBlocks) {
      doc.text(block, MARGIN_L + 6, cursor);
      cursor += block.length * 4.5;
    }
    y += cardH + 4;
  }

  // ── INDIVIDUAL RESPONSES THAT WARRANT ATTENTION ──
  if (sections.individualResponses && data.outlierItems.length > 0) {
    sectionHeading("Individual Responses That Warrant Attention");
    for (const item of data.outlierItems) {
      const rgb = hexToRgb(item.dimensionId ? (data.dimensions.find(d => d.dimensionId === item.dimensionId)?.color ?? PRIMARY_TEXT_HEX) : PRIMARY_TEXT_HEX);
      const threshold = item.score >= 85 ? "Significant (85+)" : "Notable (75+)";
      // IMPORTANT: splitTextToSize uses the CURRENT font for width calc.
      // Set font to match rendering font BEFORE splitting, or wrap widths come out wrong.
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "italic");
      const itemTextLines = doc.splitTextToSize(`"${item.itemText}"`, CONTENT_W - 10);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      const interpLines = item.interpretation ? doc.splitTextToSize(cleanMarkdown(item.interpretation), CONTENT_W - 10) : [];
      doc.setFontSize(7.5);
      const relatedLine = item.relatedPtpFacets ? doc.splitTextToSize(`Related PTP facets: ${item.relatedPtpFacets}`, CONTENT_W - 10) : [];
      const cardH = 15 + itemTextLines.length * 4 + relatedLine.length * 4 + interpLines.length * 4.5 + 10;
      ensureBlockSpace(Math.max(MIN_BLOCK_SPACE, Math.min(cardH + 4, 80)));
      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.rect(MARGIN_L, y, 1.5, cardH, "F");
      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.roundedRect(MARGIN_L + CONTENT_W - 14, y + 2, 14, 9, 1, 1, "F");
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text(String(item.score), MARGIN_L + CONTENT_W - 7, y + 8, { align: "center" });
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...BLACK);
      // Name uses narrow width (badge is present)
      const nameLines = doc.splitTextToSize(item.facetName, CONTENT_W - 20);
      doc.text(nameLines[0] ?? item.facetName, MARGIN_L + 5, y + 5);
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(rgb[0], rgb[1], rgb[2]);
      doc.text(`${item.dimensionName} · ${threshold}`, MARGIN_L + 5, y + 10);
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.setFont("helvetica", "italic");
      doc.text(itemTextLines, MARGIN_L + 5, y + 15);
      let cursor = y + 15 + itemTextLines.length * 4;
      doc.setFont("helvetica", "normal");
      if (item.relatedPtpFacets) {
        doc.setFontSize(7.5);
        doc.setTextColor(...MUTED);
        doc.text(relatedLine, MARGIN_L + 5, cursor + 3);
        cursor += relatedLine.length * 4 + 3;
      }
      if (item.interpretation) {
        doc.setFontSize(8);
        doc.setTextColor(...BLACK);
        doc.text(interpLines, MARGIN_L + 5, cursor + 3);
      }
      y += cardH + 3;
    }
    y += 2;
  }

  // ── CAFES-PTP MAPPING (coach only) ──
  if (sections.cafesPtpMapping && data.cafesPtpMapping.length > 0) {
    sectionHeading("C.A.F.E.S.–PTP Mapping");
    for (const m of data.cafesPtpMapping) {
      const rgb = hexToRgb(m.color);
      const pastelRgb = hexToRgb(m.pastelColor);

      const facetsHeader = m.ptpFacets.length > 0 ? 5 : 0;
      const facetsLines = m.ptpFacets.map(f => `• ${f.name}${f.refs ? ` (${f.refs})` : ""}`);
      const questionsHeader = m.coachingQuestions.length > 0 ? 5 : 0;
      const questionsBlocks = m.coachingQuestions.map((q, i) => doc.splitTextToSize(`${i + 1}. ${cleanMarkdown(q)}`, CONTENT_W - 12));
      const questionsH = questionsBlocks.reduce((acc, b) => acc + b.length * 4.5, 0);
      const cardH = 10 + 5 + facetsHeader + facetsLines.length * 4.5 + questionsHeader + questionsH + 8;

      checkPageBreak(cardH + 4);
      doc.setFillColor(pastelRgb[0], pastelRgb[1], pastelRgb[2]);
      doc.roundedRect(MARGIN_L, y, CONTENT_W, cardH, 2, 2, "F");
      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.rect(MARGIN_L, y, 1.5, cardH, "F");
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(rgb[0], rgb[1], rgb[2]);
      doc.text(`${m.dimensionName} — ${m.score}  (${m.band})`, MARGIN_L + 6, y + 7);
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...BLACK);
      doc.text(`Primary: ${m.primaryPtpDomain}   ·   Secondary: ${m.secondaryPtpDomain}`, MARGIN_L + 6, y + 12);

      let cursor = y + 17;
      if (m.ptpFacets.length > 0) {
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...MUTED);
        doc.text("PTP FACETS", MARGIN_L + 6, cursor);
        cursor += 4;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(...BLACK);
        for (const l of facetsLines) {
          doc.text(l, MARGIN_L + 6, cursor);
          cursor += 4.5;
        }
      }
      if (m.coachingQuestions.length > 0) {
        cursor += 2;
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...MUTED);
        doc.text("OPENING COACHING QUESTIONS", MARGIN_L + 6, cursor);
        cursor += 4;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(...BLACK);
        for (const block of questionsBlocks) {
          doc.text(block, MARGIN_L + 6, cursor);
          cursor += block.length * 4.5;
        }
      }
      y += cardH + 4;
    }
    y += 2;
  }

  // ── CROSS-ASSESSMENT INTERPRETATION ──
  if (sections.crossAssessmentInterpretation && data.crossAssessment) {
    sectionHeading("Cross-Assessment Interpretation");
    if (data.crossAssessment.interpretation) {
      bodyText(data.crossAssessment.interpretation);
      y += 3;
    }
    if (data.crossAssessment.suggestions.length > 0) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...NAVY);
      checkPageBreak(7);
      doc.text("Suggested ways to support yourself", MARGIN_L, y);
      y += 5;
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...BLACK);
      for (const s of data.crossAssessment.suggestions) {
        // Render bullet with hanging indent: text below first line aligns with text, not bullet
        const bulletX = MARGIN_L + 3;
        const textX = MARGIN_L + 7;
        const textWidth = CONTENT_W - 10;
        const textLines = doc.splitTextToSize(cleanMarkdown(s), textWidth);
        checkPageBreak(5);
        doc.text("•", bulletX, y);
        textLines.forEach((line: string, idx: number) => {
          if (idx > 0) checkPageBreak(5);
          doc.text(line, textX, y);
          y += 4.5;
        });
      }
      y += 4;
    }
  }

  // ── ASSESSMENT RESPONSES ──
  if (sections.assessmentResponses && data.assessmentResponses.length > 0) {
    sectionHeading("Assessment Responses");
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(`${data.assessmentResponses.length} responses`, MARGIN_L, y);
    y += 6;

    for (const r of data.assessmentResponses) {
      const rgb = hexToRgb(data.dimensions.find(d => d.dimensionId === r.dimensionId)?.color ?? "#021F36");
      const labelText = `Q${r.itemNumber} — ${r.facetName}`;
      const questionLines = doc.splitTextToSize(r.itemText, CONTENT_W - 20);
      const rowH = questionLines.length * 4 + 8;
      checkPageBreak(rowH + 2);

      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.rect(MARGIN_L, y, 1.5, rowH, "F");

      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...BLACK);
      doc.text(labelText, MARGIN_L + 5, y + 5);

      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...MUTED);
      doc.text(questionLines, MARGIN_L + 5, y + 10);

      if (r.hasResponse && r.score !== null) {
        doc.setFillColor(rgb[0], rgb[1], rgb[2]);
        doc.roundedRect(MARGIN_L + CONTENT_W - 12, y + rowH / 2 - 4, 12, 8, 1, 1, "F");
        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(255, 255, 255);
        doc.text(String(r.score), MARGIN_L + CONTENT_W - 6, y + rowH / 2 + 1, { align: "center" });
      } else {
        doc.setDrawColor(200, 200, 200);
        doc.roundedRect(MARGIN_L + CONTENT_W - 12, y + rowH / 2 - 4, 12, 8, 1, 1, "S");
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(...MUTED);
        doc.text("—", MARGIN_L + CONTENT_W - 6, y + rowH / 2 + 1, { align: "center" });
      }

      doc.setDrawColor(230, 230, 230);
      doc.line(MARGIN_L, y + rowH, MARGIN_L + CONTENT_W, y + rowH);
      y += rowH + 1;
    }
  }

  addFooter();

  // Stamp "Page X of Y" on every page now that the total page count is known.
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...MUTED);
    doc.text(`Page ${p} of ${totalPages}`, PAGE_W - MARGIN_R, FOOTER_Y, { align: "right" });
  }

  const lastName = data.userName.split(" ").pop() || "User";
  const dateStr = new Date().toISOString().slice(0, 10);
  const viewSuffix = data.isCoachView ? "-Coach" : "";
  if (options?.returnBlob) {
    return doc.output("blob");
  }
  doc.save(`BrainWise-${data.instrumentShortName}${viewSuffix}-${lastName}-${dateStr}.pdf`);
}
