import jsPDF from "jspdf";

// ============================================================
// Types
// ============================================================

export interface PTPDashboardPdfSections {
  overview: boolean;
  dimensions: boolean;
  interpretation: boolean;
  interventions: boolean;
}

export interface PTPDashboardPdfData {
  orgName: string;
  sliceLabel: string;
  generatedAt: string;
  participantCount: number;
  triScore: number | null;
  rsiScore: number | null;
  archetypeName: string | null;
  archetypeDescription: string | null;
  dimensions: Array<{
    dimId: string;
    name: string;
    avgScore: number;
    pctAt75: number;
    pctHigh: number;
    pctElevated: number;
    pctLow: number;
    color: string;
  }>;
  riskFlags: Array<{
    id: string;
    level: string;
    title: string;
    summary: string;
    detail: string;
  }>;
  businessMeaning: string | null;
  benefits: string | null;
  risks: string | null;
  nextSteps: string | null;
  reassessmentNote: string | null;
  interventions: Array<{
    title: string;
    description: string;
    targetDimensions: string[];
    priority: string;
    timeHorizon: string;
    interventionType: string;
  }>;
  exportSections: PTPDashboardPdfSections;
}

// ============================================================
// Constants
// ============================================================

const NAVY: [number, number, number] = [2, 31, 54];
const ORANGE: [number, number, number] = [245, 116, 26];
const PURPLE: [number, number, number] = [60, 9, 108];
const SAND: [number, number, number] = [249, 247, 241];
const MUTED: [number, number, number] = [110, 110, 120];
const TEXT: [number, number, number] = [30, 30, 35];
const RED: [number, number, number] = [163, 45, 45];
const GREEN_PASTEL: [number, number, number] = [200, 235, 215];
const AMBER_PASTEL: [number, number, number] = [250, 230, 195];
const RED_PASTEL: [number, number, number] = [248, 210, 210];
const PURPLE_PASTEL: [number, number, number] = [225, 215, 240];
const NAVY_PASTEL: [number, number, number] = [215, 225, 240];

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN_L = 15;
const MARGIN_R = 15;
const MARGIN_T = 20;
const MARGIN_B = 25;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;

const DIM_NAME_MAP: Record<string, string> = {
  "DIM-PTP-01": "Protection",
  "DIM-PTP-02": "Participation",
  "DIM-PTP-03": "Prediction",
  "DIM-PTP-04": "Purpose",
  "DIM-PTP-05": "Pleasure",
};

// ============================================================
// Helpers
// ============================================================

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

function activationLabel(score: number): string {
  if (score >= 76) return "High";
  if (score >= 50) return "Elevated";
  return "Low";
}

export function generatePTPDashboardPdf(data: PTPDashboardPdfData): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN_T;

  const setFill = (rgb: [number, number, number]) =>
    doc.setFillColor(rgb[0], rgb[1], rgb[2]);
  const setText = (rgb: [number, number, number]) =>
    doc.setTextColor(rgb[0], rgb[1], rgb[2]);
  const setDraw = (rgb: [number, number, number]) =>
    doc.setDrawColor(rgb[0], rgb[1], rgb[2]);

  const addFooter = () => {
    const footerY = PAGE_H - 12;
    setText(MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    const date = new Date().toLocaleDateString();
    doc.text(
      `Generated by BrainWise | ${date} | Confidential`,
      PAGE_W / 2,
      footerY,
      { align: "center" },
    );
  };

  const newPage = () => {
    addFooter();
    doc.addPage();
    y = MARGIN_T;
  };

  const checkPageBreak = (needed: number) => {
    if (y + needed > PAGE_H - MARGIN_B) {
      newPage();
    }
  };

  const sectionHeading = (label: string) => {
    checkPageBreak(15);
    setText(NAVY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(label, MARGIN_L, y);
    setDraw(ORANGE);
    doc.setLineWidth(0.8);
    doc.line(MARGIN_L, y + 2, MARGIN_L + 25, y + 2);
    y += 10;
  };

  const wrappedText = (
    text: string,
    x: number,
    startY: number,
    maxWidth: number,
    lineHeight: number,
    fontSize: number,
    color: [number, number, number],
    style: "normal" | "bold" | "italic" = "normal",
  ): number => {
    setText(color);
    doc.setFont("helvetica", style);
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, maxWidth) as string[];
    let cy = startY;
    for (const line of lines) {
      if (cy > PAGE_H - MARGIN_B) {
        addFooter();
        doc.addPage();
        cy = MARGIN_T;
      }
      doc.text(line, x, cy);
      cy += lineHeight;
    }
    return cy;
  };

  // ============================================================
  // COVER PAGE
  // ============================================================

  // Navy band
  setFill(NAVY);
  doc.rect(0, 0, PAGE_W, 75, "F");

  setText([255, 255, 255]);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.text("BrainWise", MARGIN_L, 35);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(13);
  doc.text("PTP · Personal Threat Profile Dashboard", MARGIN_L, 48);

  // Two columns at y=100
  // Left column
  setText(MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Organization", MARGIN_L, 100);

  setText(NAVY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(data.orgName || "Organization", MARGIN_L, 108);

  setText(MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Slice", MARGIN_L, 122);

  setText(TEXT);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(data.sliceLabel, MARGIN_L, 130);

  // Right column - scores
  const rightX = PAGE_W / 2 + 10;
  if (data.triScore !== null) {
    setText(NAVY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(32);
    doc.text(data.triScore.toFixed(1), rightX, 110);

    setText(MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Threat Reactivity Index", rightX, 117);
  }

  if (data.rsiScore !== null) {
    setText(PURPLE);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(32);
    doc.text(data.rsiScore.toFixed(1), rightX, 140);

    setText(MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("Reward Sensitivity Index", rightX, 147);
  }

  // Archetype box at y=170
  if (data.archetypeName) {
    setFill(SAND);
    doc.roundedRect(MARGIN_L, 170, CONTENT_W, 35, 3, 3, "F");

    setText(MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("THREAT PROFILE ARCHETYPE", MARGIN_L + 6, 178);

    setText(NAVY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(data.archetypeName, MARGIN_L + 6, 188);

    if (data.archetypeDescription) {
      wrappedText(
        data.archetypeDescription,
        MARGIN_L + 6,
        196,
        CONTENT_W - 12,
        4.5,
        9,
        MUTED,
      );
    }
  }

  // Generated at y=220
  setText(MUTED);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Generated", MARGIN_L, 220);

  setText(TEXT);
  doc.setFontSize(11);
  doc.text(
    `${data.generatedAt} · ${data.participantCount} participants`,
    MARGIN_L,
    228,
  );

  // Disclaimer box
  setFill([245, 245, 245]);
  doc.roundedRect(MARGIN_L, 245, CONTENT_W, 30, 2, 2, "F");
  setText(MUTED);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  const disclaimer =
    "This report contains aggregated, de-identified PTP assessment data intended for organizational decision-making. Individual responses are confidential. Interpretations are AI-assisted and should be reviewed alongside qualitative context.";
  wrappedText(disclaimer, MARGIN_L + 4, 252, CONTENT_W - 8, 4, 8, MUTED, "italic");

  addFooter();

  // ============================================================
  // OVERVIEW PAGE
  // ============================================================
  if (data.exportSections.overview) {
    doc.addPage();
    y = MARGIN_T;

    sectionHeading("Overview");

    // Five dimension cards in a row
    const cardW = (CONTENT_W - 4 * 2) / 5;
    const cardH = 32;
    const cardY = y;
    data.dimensions.forEach((dim, i) => {
      const cardX = MARGIN_L + i * (cardW + 2);
      const dimColor = hexToRgb(dim.color);

      setFill(SAND);
      doc.roundedRect(cardX, cardY, cardW, cardH, 2, 2, "F");

      setText(dimColor);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.text(dim.name, cardX + cardW / 2, cardY + 6, { align: "center" });

      doc.setFontSize(22);
      doc.text(dim.avgScore.toFixed(1), cardX + cardW / 2, cardY + 19, {
        align: "center",
      });

      setText(MUTED);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.text(activationLabel(dim.avgScore), cardX + cardW / 2, cardY + 27, {
        align: "center",
      });
    });
    y += cardH + 8;

    // TRI/RSI summary
    if (data.triScore !== null || data.rsiScore !== null) {
      checkPageBreak(20);
      const triText =
        data.triScore !== null
          ? `TRI: ${data.triScore.toFixed(1)} · higher = less reactive`
          : "";
      const rsiText =
        data.rsiScore !== null
          ? `RSI: ${data.rsiScore.toFixed(1)} · higher = stronger motivation`
          : "";

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      if (triText) {
        setText(NAVY);
        doc.text(triText, PAGE_W / 2, y, { align: "center" });
        y += 6;
      }
      if (rsiText) {
        setText(PURPLE);
        doc.text(rsiText, PAGE_W / 2, y, { align: "center" });
        y += 6;
      }
      y += 6;
    }

    // Risk flags
    if (data.riskFlags.length > 0) {
      sectionHeading("Risk Flags");
      for (const flag of data.riskFlags) {
        const accent = flag.level === "high" ? RED : ORANGE;
        const summaryLines = doc.splitTextToSize(
          flag.summary,
          CONTENT_W - 14,
        ) as string[];
        const detailLines = doc.splitTextToSize(
          flag.detail,
          CONTENT_W - 14,
        ) as string[];
        const blockH =
          16 + summaryLines.length * 5 + detailLines.length * 4.5 + 6;

        checkPageBreak(blockH + 4);

        setFill(SAND);
        doc.roundedRect(MARGIN_L, y, CONTENT_W, blockH, 2, 2, "F");

        // Left border
        setFill(accent);
        doc.rect(MARGIN_L, y, 1.2, blockH, "F");

        let cy = y + 6;
        setText(accent);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.text(flag.level.toUpperCase(), MARGIN_L + 6, cy);
        cy += 5;

        setText(NAVY);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.text(flag.title, MARGIN_L + 6, cy);
        cy += 6;

        setText(MUTED);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        for (const line of summaryLines) {
          doc.text(line, MARGIN_L + 6, cy);
          cy += 5;
        }

        setText(TEXT);
        doc.setFontSize(10);
        for (const line of detailLines) {
          doc.text(line, MARGIN_L + 6, cy);
          cy += 4.5;
        }

        y += blockH + 4;
      }
    }
  }

  // ============================================================
  // DIMENSIONS PAGE
  // ============================================================
  if (data.exportSections.dimensions) {
    doc.addPage();
    y = MARGIN_T;

    sectionHeading("Dimensions");

    const renderDimCard = (
      dim: PTPDashboardPdfData["dimensions"][number],
      weightLabel: string,
      weightColor: [number, number, number],
    ) => {
      const cardH = 38;
      checkPageBreak(cardH + 4);

      setFill(SAND);
      doc.roundedRect(MARGIN_L, y, CONTENT_W, cardH, 2, 2, "F");

      const dimColor = hexToRgb(dim.color);

      // Name + score
      setText(dimColor);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.text(dim.name, MARGIN_L + 6, y + 9);

      doc.setFontSize(22);
      doc.text(dim.avgScore.toFixed(1), MARGIN_L + 6, y + 22);

      // Weight badge
      setFill(weightColor);
      doc.roundedRect(MARGIN_L + 50, y + 5, 22, 6, 1, 1, "F");
      setText([255, 255, 255]);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.text(weightLabel, MARGIN_L + 61, y + 9.2, { align: "center" });

      // pct at 75
      setText(MUTED);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.text(
        `${dim.pctAt75.toFixed(0)}% scoring ≥ 75 (high activation)`,
        MARGIN_L + 50,
        y + 17,
      );

      // Activation label
      setText(dimColor);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.text(activationLabel(dim.avgScore), MARGIN_L + 50, y + 22);

      // Distribution bar
      const barX = MARGIN_L + 6;
      const barY = y + 28;
      const barW = CONTENT_W - 12;
      const barH = 6;
      const total =
        Math.max(dim.pctLow + dim.pctElevated + dim.pctHigh, 0.0001);
      const lowW = (dim.pctLow / total) * barW;
      const elevW = (dim.pctElevated / total) * barW;
      const highW = (dim.pctHigh / total) * barW;

      setFill(GREEN_PASTEL);
      doc.rect(barX, barY, lowW, barH, "F");
      setFill(AMBER_PASTEL);
      doc.rect(barX + lowW, barY, elevW, barH, "F");
      setFill(RED_PASTEL);
      doc.rect(barX + lowW + elevW, barY, highW, barH, "F");

      y += cardH + 4;
    };

    // Threat
    setText(ORANGE);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("THREAT DIMENSIONS", MARGIN_L, y);
    y += 6;

    const threatWeights: Record<string, string> = {
      "DIM-PTP-01": "TRI 25%",
      "DIM-PTP-02": "TRI 30%",
      "DIM-PTP-03": "TRI 45%",
    };
    for (const dimId of ["DIM-PTP-01", "DIM-PTP-02", "DIM-PTP-03"]) {
      const dim = data.dimensions.find((d) => d.dimId === dimId);
      if (dim) renderDimCard(dim, threatWeights[dimId], ORANGE);
    }

    y += 4;

    // Reward
    checkPageBreak(15);
    setText(PURPLE);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("REWARD DIMENSIONS", MARGIN_L, y);
    y += 6;

    const rewardWeights: Record<string, string> = {
      "DIM-PTP-04": "RSI 60%",
      "DIM-PTP-05": "RSI 40%",
    };
    for (const dimId of ["DIM-PTP-04", "DIM-PTP-05"]) {
      const dim = data.dimensions.find((d) => d.dimId === dimId);
      if (dim) renderDimCard(dim, rewardWeights[dimId], PURPLE);
    }
  }

  // ============================================================
  // AI INTERPRETATION PAGE
  // ============================================================
  if (data.exportSections.interpretation) {
    doc.addPage();
    y = MARGIN_T;

    sectionHeading("AI Interpretation");

    // Archetype card
    if (data.archetypeName) {
      const descLines = data.archetypeDescription
        ? (doc.splitTextToSize(
            data.archetypeDescription,
            CONTENT_W - 12,
          ) as string[])
        : [];
      const cardH = 18 + descLines.length * 5;
      checkPageBreak(cardH + 4);

      setFill(SAND);
      doc.roundedRect(MARGIN_L, y, CONTENT_W, cardH, 2, 2, "F");

      setText(NAVY);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.text("THREAT PROFILE", MARGIN_L + 6, y + 7);

      doc.setFontSize(13);
      doc.text(data.archetypeName, MARGIN_L + 6, y + 14);

      if (descLines.length > 0) {
        setText(MUTED);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        let dy = y + 20;
        for (const line of descLines) {
          doc.text(line, MARGIN_L + 6, dy);
          dy += 5;
        }
      }

      y += cardH + 6;
    }

    const sections: Array<{ label: string; text: string | null }> = [
      { label: "What this means for your organization", text: data.businessMeaning },
      { label: "Potential benefits", text: data.benefits },
      { label: "Potential risks if unaddressed", text: data.risks },
      { label: "Recommended next steps", text: data.nextSteps },
      { label: "Reassessment", text: data.reassessmentNote },
    ];

    for (const s of sections) {
      if (!s.text) continue;
      checkPageBreak(20);

      // Orange left bar + label
      setFill(ORANGE);
      doc.rect(MARGIN_L, y - 4, 1.2, 7, "F");
      setText(NAVY);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(s.label, MARGIN_L + 4, y);
      y += 6;

      y = wrappedText(s.text, MARGIN_L, y, CONTENT_W, 5, 11, TEXT);
      y += 6;
    }
  }

  // ============================================================
  // INTERVENTIONS PAGE
  // ============================================================
  if (data.exportSections.interventions) {
    doc.addPage();
    y = MARGIN_T;

    sectionHeading("Structured Interventions");

    if (data.interventions.length === 0) {
      setText(MUTED);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(11);
      doc.text("No structured interventions available.", MARGIN_L, y);
    }

    for (const iv of data.interventions) {
      const descLines = doc.splitTextToSize(
        iv.description,
        CONTENT_W - 12,
      ) as string[];
      const targetNames = iv.targetDimensions
        .map((d) => DIM_NAME_MAP[d] || d)
        .join(" · ");
      const cardH = 26 + descLines.length * 5 + 6;

      checkPageBreak(cardH + 4);

      setFill(SAND);
      doc.roundedRect(MARGIN_L, y, CONTENT_W, cardH, 2, 2, "F");

      // Title
      setText(NAVY);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.text(iv.title, MARGIN_L + 6, y + 9);

      // Badges row
      const badgeY = y + 14;
      let badgeX = MARGIN_L + 6;

      const drawBadge = (
        text: string,
        bg: [number, number, number],
        fg: [number, number, number],
      ) => {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        const textW = doc.getTextWidth(text);
        const padX = 2.5;
        const w = textW + padX * 2;
        const h = 5;
        setFill(bg);
        doc.roundedRect(badgeX, badgeY - 3.5, w, h, 1, 1, "F");
        setText(fg);
        doc.text(text, badgeX + padX, badgeY);
        badgeX += w + 2;
      };

      const priorityColors: Record<
        string,
        { bg: [number, number, number]; fg: [number, number, number] }
      > = {
        high: { bg: RED_PASTEL, fg: RED },
        medium: { bg: AMBER_PASTEL, fg: [133, 77, 14] },
        low: { bg: GREEN_PASTEL, fg: [15, 110, 86] },
      };
      const pc = priorityColors[iv.priority] || priorityColors.medium;
      drawBadge(iv.priority.toUpperCase(), pc.bg, pc.fg);
      drawBadge(iv.timeHorizon.toUpperCase(), PURPLE_PASTEL, PURPLE);
      drawBadge(iv.interventionType.toUpperCase(), NAVY_PASTEL, NAVY);

      // Description
      setText(TEXT);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      let dy = y + 20;
      for (const line of descLines) {
        doc.text(line, MARGIN_L + 6, dy);
        dy += 5;
      }

      // Targets
      setText(MUTED);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.text(`Targets: ${targetNames}`, MARGIN_L + 6, dy + 2);

      y += cardH + 4;
    }
  }

  addFooter();

  // ============================================================
  // Save
  // ============================================================
  const dateStr = new Date().toISOString().slice(0, 10);
  const safeOrg = (data.orgName || "Organization").replace(/[^a-zA-Z0-9]+/g, "-");
  doc.save(`BrainWise-PTP-Dashboard-${safeOrg}-${dateStr}.pdf`);
}
