import jsPDF from "jspdf";
import type { PdfSections } from "@/components/results/ExportPdfModal";

// ── Types ──
interface DimensionRow {
  name: string;
  score: number;
  band: string;
  color: string;
}

interface FacetRow {
  text: string;
  score: number;
  color: string;
}

export interface PdfData {
  userName: string;
  instrumentName: string;
  instrumentShortName: string;
  instrumentVersion: string;
  dateTaken: string;
  dimensions: DimensionRow[];
  statCards: { label: string; value: string }[];
  narrative: string | null;
  elevatedFacets: FacetRow[];
  suppressedFacets: FacetRow[];
  recommendations: string[];
  isSliderInstrument: boolean;
}

const PAGE_W = 210; // A4 mm
const PAGE_H = 297;
const MARGIN_L = 15;
const MARGIN_R = 15;
const MARGIN_T = 20;
const MARGIN_B = 25;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;
const FOOTER_Y = PAGE_H - 12;

const PRIMARY = [31, 78, 121] as const; // #1F4E79
const MUTED = [120, 120, 120] as const;
const BLACK = [30, 30, 30] as const;
const WHITE = [255, 255, 255] as const;
const LIGHT_BG = [245, 247, 250] as const;

export function generateResultsPdf(data: PdfData, sections: PdfSections): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN_T;

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  // ── Helpers ──
  const addFooter = () => {
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(`Generated by BrainWise | ${today} | Confidential`, PAGE_W / 2, FOOTER_Y, { align: "center" });
    doc.setDrawColor(220, 220, 220);
    doc.line(MARGIN_L, FOOTER_Y - 3, PAGE_W - MARGIN_R, FOOTER_Y - 3);
  };

  const checkPageBreak = (needed: number): void => {
    if (y + needed > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      y = MARGIN_T;
    }
  };

  const sectionHeading = (title: string) => {
    checkPageBreak(15);
    y += 4;
    doc.setFontSize(13);
    doc.setTextColor(...PRIMARY);
    doc.setFont("helvetica", "bold");
    doc.text(title, MARGIN_L, y);
    y += 2;
    doc.setDrawColor(...PRIMARY);
    doc.setLineWidth(0.5);
    doc.line(MARGIN_L, y, MARGIN_L + CONTENT_W, y);
    y += 6;
  };

  const wrapText = (text: string, fontSize: number, maxWidth: number, bold = false): string[] => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    return doc.splitTextToSize(text, maxWidth);
  };

  // ── Header ──
  doc.setFontSize(20);
  doc.setTextColor(...PRIMARY);
  doc.setFont("helvetica", "bold");
  doc.text("BrainWise", MARGIN_L, y);
  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(...BLACK);
  doc.setFont("helvetica", "normal");
  doc.text(data.userName, MARGIN_L, y);
  y += 5;
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(`${data.instrumentName}  |  ${data.dateTaken}  |  Version ${data.instrumentVersion}`, MARGIN_L, y);
  y += 8;

  // ── Disclaimer ──
  doc.setDrawColor(220, 220, 220);
  doc.setFillColor(...LIGHT_BG);
  const disclaimerText = "This report is generated by an AI model and is intended for personal reflection only. It does not constitute clinical diagnosis or professional psychological advice. Results should be interpreted in conjunction with qualified professional guidance.";
  const disclaimerLines = wrapText(disclaimerText, 7.5, CONTENT_W - 8);
  const disclaimerH = disclaimerLines.length * 3.5 + 4;
  doc.roundedRect(MARGIN_L, y, CONTENT_W, disclaimerH, 2, 2, "FD");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(disclaimerLines, MARGIN_L + 4, y + 4);
  y += disclaimerH + 6;

  // ── Profile Overview ──
  if (sections.profileOverview) {
    sectionHeading("Profile Overview");

    // Stat cards row
    const cardW = (CONTENT_W - 6) / 3;
    data.statCards.forEach((card, i) => {
      const x = MARGIN_L + i * (cardW + 3);
      doc.setFillColor(...LIGHT_BG);
      doc.roundedRect(x, y, cardW, 14, 1.5, 1.5, "F");
      doc.setFontSize(7);
      doc.setTextColor(...MUTED);
      doc.text(card.label, x + 3, y + 5);
      doc.setFontSize(9);
      doc.setTextColor(...BLACK);
      doc.setFont("helvetica", "bold");
      // Truncate value to fit card
      const truncVal = card.value.length > 22 ? card.value.slice(0, 20) + "…" : card.value;
      doc.text(truncVal, x + 3, y + 11);
      doc.setFont("helvetica", "normal");
    });
    y += 20;

    // Dimension scores table
    checkPageBreak(15 + data.dimensions.length * 8);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...BLACK);

    // Table header
    const colName = MARGIN_L;
    const colScore = MARGIN_L + CONTENT_W * 0.5;
    const colBar = MARGIN_L + CONTENT_W * 0.62;
    const colBand = MARGIN_L + CONTENT_W * 0.87;

    doc.text("Dimension", colName, y);
    doc.text("Score", colScore, y);
    doc.text("", colBar, y);
    doc.text("Band", colBand, y);
    y += 2;
    doc.setDrawColor(200, 200, 200);
    doc.line(MARGIN_L, y, MARGIN_L + CONTENT_W, y);
    y += 4;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    const maxScore = data.isSliderInstrument ? 100 : 4;
    const barMaxW = CONTENT_W * 0.22;

    for (const dim of data.dimensions) {
      checkPageBreak(8);
      // Alternate row bg
      const rowIdx = data.dimensions.indexOf(dim);
      if (rowIdx % 2 === 0) {
        doc.setFillColor(250, 250, 252);
        doc.rect(MARGIN_L, y - 3.5, CONTENT_W, 7, "F");
      }

      doc.setTextColor(...BLACK);
      const nameLines = wrapText(dim.name, 8.5, CONTENT_W * 0.48);
      doc.text(nameLines[0], colName, y);

      doc.text(dim.score.toFixed(1), colScore, y);

      // Score bar
      const barW = Math.max(1, (dim.score / maxScore) * barMaxW);
      const rgb = hexToRgb(dim.color);
      doc.setFillColor(rgb[0], rgb[1], rgb[2]);
      doc.roundedRect(colBar, y - 2.5, barW, 4, 1, 1, "F");

      // Band label
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.text(formatBand(dim.band), colBand, y);
      doc.setFontSize(8.5);

      y += 7;
    }
    y += 4;
  }

  // ── AI Narrative ──
  if (sections.aiNarrative && data.narrative) {
    sectionHeading("Profile Interpretation");
    renderNarrative(doc, data.narrative, false);
  }

  // ── Driving Facet Scores ──
  if (sections.drivingFacetScores && (data.elevatedFacets.length > 0 || data.suppressedFacets.length > 0)) {
    sectionHeading("Driving Facet Scores");

    if (data.elevatedFacets.length > 0) {
      renderFacetTable(doc, "Elevated Facets", data.elevatedFacets);
    }
    if (data.suppressedFacets.length > 0) {
      renderFacetTable(doc, "Suppressed Facets", data.suppressedFacets);
    }
  }

  // ── Driving Facet Insights (from narrative) ──
  if (sections.drivingFacetInsights && data.narrative) {
    const insightsText = extractFacetInsights(data.narrative);
    if (insightsText) {
      sectionHeading("Driving Facet Insights");
      renderNarrative(doc, insightsText, true);
    }
  }

  // ── Cross-Assessment Recommendations ──
  if (sections.crossAssessmentRecs && data.recommendations.length > 0) {
    sectionHeading("Cross-Assessment Recommendations");
    checkPageBreak(10);
    doc.setFontSize(8.5);
    doc.setTextColor(...BLACK);
    doc.text("Based on your results, we recommend exploring:", MARGIN_L, y);
    y += 6;
    for (const rec of data.recommendations) {
      checkPageBreak(8);
      doc.setFillColor(...PRIMARY);
      doc.circle(MARGIN_L + 2, y - 1, 1, "F");
      doc.setTextColor(...BLACK);
      doc.text(rec, MARGIN_L + 6, y);
      y += 6;
    }
  }

  // Final footer
  addFooter();

  // ── Save ──
  const lastName = data.userName.split(" ").pop() || "User";
  const dateStr = new Date().toISOString().slice(0, 10);
  const shortName = data.instrumentShortName || data.instrumentName.replace(/\s+/g, "");
  doc.save(`BrainWise-${shortName}-${lastName}-${dateStr}.pdf`);

  // ── Inner render helpers (closure over doc, y, checkPageBreak) ──
  function renderNarrative(d: jsPDF, text: string, insightsOnly: boolean) {
    const lines = text.split("\n");
    let inFacetSection = false;
    let skipFacetInsightsBlock = false;

    for (const raw of lines) {
      const trimmed = raw.trim();

      if (trimmed.startsWith("## ")) {
        if (!insightsOnly) {
          skipFacetInsightsBlock = isFacetInsightsTopHeading(trimmed);
          if (skipFacetInsightsBlock) {
            inFacetSection = false;
            continue;
          }
        } else {
          skipFacetInsightsBlock = false;
        }
      }

      if (!insightsOnly && skipFacetInsightsBlock) {
        continue;
      }

      if (!trimmed) {
        if (!insightsOnly || inFacetSection) {
          y += 2;
        }
        continue;
      }

      if (trimmed.startsWith("### ")) {
        if (isFacetScoreGroupHeading(trimmed)) {
          inFacetSection = false;
          continue;
        }
        inFacetSection = true;
      } else if (trimmed.startsWith("## ")) {
        inFacetSection = false;
      }

      if (insightsOnly && !inFacetSection) continue;
      if (!insightsOnly && inFacetSection) continue;

      if (trimmed.startsWith("## ")) {
        const headingText = trimmed.replace(/^##\s*/, '');
        if (headingText === 'Elevated Facets' || headingText === 'Suppressed Facets' || headingText === 'Driving Facet Insights') {
          continue;
        }
        checkPageBreak(12);
        y += 3;
        d.setFontSize(11);
        d.setTextColor(...PRIMARY);
        d.setFont("helvetica", "bold");
        d.text(trimmed.replace(/^##\s*/, "").replace(/\*\*/g, ""), MARGIN_L, y);
        y += 6;
        continue;
      }

      if (trimmed.startsWith("### ")) {
        checkPageBreak(10);
        y += 2;
        d.setFontSize(9.5);
        d.setTextColor(...PRIMARY);
        d.setFont("helvetica", "bold");
        d.text(trimmed.replace(/^###\s*/, "").replace(/\*\*/g, ""), MARGIN_L, y);
        y += 5;
        continue;
      }

      // Bold label lines like **Impact on Self:**
      const labelMatch = trimmed.match(/^\*\*(.+?:)\*\*$/);
      if (labelMatch) {
        checkPageBreak(8);
        d.setFontSize(8);
        d.setTextColor(...MUTED);
        d.setFont("helvetica", "bold");
        d.text(labelMatch[1].toUpperCase(), MARGIN_L, y);
        d.setFont("helvetica", "normal");
        y += 5;
        continue;
      }

      // Emoji bullets
      const emojiMatch = trimmed.match(/^(✅|❌)\s*(.+)$/);
      if (emojiMatch) {
        checkPageBreak(8);
        d.setFontSize(8.5);
        d.setTextColor(...BLACK);
        d.setFont("helvetica", "normal");
        const icon = emojiMatch[1] === "✅" ? "+" : "-";
        const rgb = emojiMatch[1] === "✅" ? [34, 139, 34] as const : [200, 50, 50] as const;
        d.setTextColor(rgb[0], rgb[1], rgb[2]);
        d.setFont("helvetica", "bold");
        d.text(icon, MARGIN_L + 2, y);
        d.setTextColor(...BLACK);
        d.setFont("helvetica", "normal");
        const bulletLines = wrapText(cleanMarkdown(emojiMatch[2]), 8.5, CONTENT_W - 10);
        for (const bl of bulletLines) {
          checkPageBreak(5);
          d.text(bl, MARGIN_L + 7, y);
          y += 4;
        }
        y += 1;
        continue;
      }

      // Bullet lines
      const bulletMatch = trimmed.match(/^[-*]\s+(.+)$/);
      if (bulletMatch) {
        checkPageBreak(8);
        d.setFontSize(8.5);
        d.setTextColor(...BLACK);
        d.setFont("helvetica", "normal");
        d.setFillColor(...PRIMARY);
        d.circle(MARGIN_L + 2, y - 1, 0.8, "F");
        const bulletLines = wrapText(cleanMarkdown(bulletMatch[1]), 8.5, CONTENT_W - 10);
        for (const bl of bulletLines) {
          checkPageBreak(5);
          d.text(bl, MARGIN_L + 7, y);
          y += 4;
        }
        y += 1;
        continue;
      }

      // Regular text
      d.setFontSize(8.5);
      d.setTextColor(...BLACK);
      d.setFont("helvetica", "normal");
      const textLines = wrapText(cleanMarkdown(trimmed), 8.5, CONTENT_W);
      for (const tl of textLines) {
        checkPageBreak(5);
        d.text(tl, MARGIN_L, y);
        y += 4;
      }
      y += 1;
    }
    y += 4;
  }

  function renderFacetTable(d: jsPDF, title: string, facets: FacetRow[]) {
    checkPageBreak(12 + facets.length * 7);
    d.setFontSize(9);
    d.setFont("helvetica", "bold");
    d.setTextColor(...BLACK);
    d.text(title, MARGIN_L, y);
    y += 5;

    // Table header
    d.setFontSize(7.5);
    d.setTextColor(...MUTED);
    d.text("Facet", MARGIN_L, y);
    d.text("Score", MARGIN_L + CONTENT_W * 0.75, y);
    y += 2;
    d.setDrawColor(200, 200, 200);
    d.line(MARGIN_L, y, MARGIN_L + CONTENT_W, y);
    y += 4;

    d.setFont("helvetica", "normal");
    d.setFontSize(8);

    for (let i = 0; i < facets.length; i++) {
      checkPageBreak(7);
      const f = facets[i];
      if (i % 2 === 0) {
        d.setFillColor(250, 250, 252);
        d.rect(MARGIN_L, y - 3, CONTENT_W, 6, "F");
      }

      // Color indicator
      const rgb = hexToRgb(f.color);
      d.setFillColor(rgb[0], rgb[1], rgb[2]);
      d.circle(MARGIN_L + 2, y - 1, 1.5, "F");

      // Truncated text
      const truncText = f.text.length > 80 ? f.text.slice(0, 77) + "…" : f.text;
      d.setTextColor(...BLACK);
      d.text(truncText, MARGIN_L + 6, y);

      d.text(f.score.toFixed(1), MARGIN_L + CONTENT_W * 0.75, y);
      y += 6;
    }
    y += 6;
  }
}

// ── Utilities ──

function cleanMarkdown(text: string): string {
  return text.replace(/\*\*(.+?)\*\*/g, "$1");
}

function isFacetInsightsTopHeading(text: string): boolean {
  return /^##\s+driving facet insights\b/i.test(text);
}

function isFacetScoreGroupHeading(text: string): boolean {
  return /^#{2,3}\s+(elevated|suppressed)\s+facets\b/i.test(text);
}

function formatBand(band: string): string {
  return band
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

function extractFacetInsights(narrative: string): string | null {
  const lines = narrative.split('\n');
  const result: string[] = [];
  let inInsightsSection = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // Start capturing after ## Driving Facet Insights
    if (trimmed === '## Driving Facet Insights') {
      inInsightsSection = true;
      continue;
    }

    if (!inInsightsSection) continue;

    // Skip these exact lines
    if (trimmed === '## Elevated Facets') continue;
    if (trimmed === '## Suppressed Facets') continue;
    if (trimmed === '## Driving Facet Insights') continue;
    if (trimmed === 'Elevated Facets' || trimmed === 'Suppressed Facets') continue;

    result.push(line);
  }

  const hasContent = result.some(l => /[✅❌]/.test(l));
  return hasContent ? result.join('\n') : null;
}
