import jsPDF from "jspdf";

const NAVY: [number, number, number] = [2, 31, 54];
const ORANGE: [number, number, number] = [245, 116, 26]; // match generateResultsPdf.ts ORANGE
const MUTED: [number, number, number] = [109, 104, 117];
const BLACK: [number, number, number] = [30, 30, 30];
const SAND_BG: [number, number, number] = [249, 247, 241];

interface Block { heading: string; items: string[] }
interface Section { label?: string; snapshot: string; blocks: Block[] }
export interface OnePager {
  audience: "work" | "therapist" | "partner" | "friend";
  title: string; disclaimer?: string; sections: Section[]; nutshell: string;
}

export async function generateOnePagerPdf(onePager: OnePager, opts: { userName: string; dateTaken?: string }): Promise<void> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const { registerPdfFonts } = await import("./pdfFonts");
  await registerPdfFonts(doc);

  const PAGE_W = doc.internal.pageSize.getWidth();
  const PAGE_H = doc.internal.pageSize.getHeight();
  const M = 16;
  const CONTENT_W = PAGE_W - M * 2;

  const logo = await (async () => {
    try {
      const res = await fetch("/logo-orange-white.png");
      if (!res.ok) return null;
      const blob = await res.blob();
      return await new Promise<string>((resolve) => {
        const r = new FileReader(); r.onloadend = () => resolve(r.result as string); r.readAsDataURL(blob);
      });
    } catch { return null; }
  })();

  // Header band — sized so the whole logo sits inside it (no spill onto the title).
  const BAND_H = 40;
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, PAGE_W, BAND_H, "F");
  if (logo) {
    const logoH = 24;
    let logoW = 42;
    try { const p = doc.getImageProperties(logo); logoW = (p.width / p.height) * logoH; } catch { /* fallback width */ }
    doc.addImage(logo, "PNG", M, (BAND_H - logoH) / 2, logoW, logoH, undefined, "FAST");
  } else {
    doc.setFont("Poppins", "extrabold"); doc.setFontSize(18); doc.setTextColor(255, 255, 255);
    doc.text("BrainWise", M, BAND_H / 2 + 3);
  }
  doc.setFont("Montserrat", "semibold"); doc.setFontSize(9); doc.setTextColor(...ORANGE); doc.setCharSpace(1.2);
  doc.text("ONE-PAGE SNAPSHOT", PAGE_W - M, BAND_H / 2 + 1, { align: "right" }); doc.setCharSpace(0);

  let y = BAND_H + 12;

  doc.setFont("Poppins", "bold"); doc.setFontSize(15); doc.setTextColor(...NAVY);
  const tl = doc.splitTextToSize(onePager.title, CONTENT_W); doc.text(tl, M, y); y += tl.length * 7 + 2;

  if (onePager.disclaimer) {
    doc.setFont("Montserrat", "normal"); doc.setFontSize(8); doc.setTextColor(...MUTED);
    const dl = doc.splitTextToSize(onePager.disclaimer, CONTENT_W); doc.text(dl, M, y); y += dl.length * 4 + 4;
  } else { y += 2; }

  // Render one section (snapshot + blocks) in a column of width w at x, from startY. Returns endY.
  const renderSection = (s: Section, x: number, w: number, startY: number, compact: boolean): number => {
    let yy = startY;
    const snapSize = compact ? 8.5 : 9.5;
    const bodySize = compact ? 8.5 : 9;
    const lh = compact ? 4 : 4.6;
    if (s.label) {
      doc.setFont("Poppins", "bold"); doc.setFontSize(10.5); doc.setTextColor(...ORANGE);
      doc.text(s.label.toUpperCase(), x, yy); yy += 6.5;
    }
    doc.setFont("Montserrat", "normal"); doc.setFontSize(snapSize); doc.setTextColor(...BLACK);
    const snap = doc.splitTextToSize(s.snapshot, w); doc.text(snap, x, yy); yy += snap.length * lh + 3;
    for (const b of s.blocks) {
      doc.setFont("Poppins", "bold"); doc.setFontSize(bodySize + 0.5); doc.setTextColor(...NAVY);
      doc.text(b.heading, x, yy); yy += lh + 1;
      doc.setFont("Montserrat", "normal"); doc.setFontSize(bodySize); doc.setTextColor(...BLACK);
      for (const it of b.items) {
        const lines = doc.splitTextToSize(it, w - 4);
        doc.text("•", x, yy); doc.text(lines, x + 3.5, yy); yy += lines.length * lh + 1.2;
      }
      yy += 1.8;
    }
    return yy;
  };

  if (onePager.sections.length > 1) {
    const gutter = 8;
    const colW = (CONTENT_W - gutter) / 2;
    const leftEnd = renderSection(onePager.sections[0], M, colW, y, true);
    const rightEnd = renderSection(onePager.sections[1], M + colW + gutter, colW, y, true);
    y = Math.max(leftEnd, rightEnd) + 4;
  } else {
    y = renderSection(onePager.sections[0], M, CONTENT_W, y, false) + 3;
  }

  // Nutshell (nudge up to stay on page if content ran long)
  const nut = doc.splitTextToSize("In a nutshell: " + onePager.nutshell, CONTENT_W - 8);
  const nutH = nut.length * 4.6 + 8;
  if (y + nutH > PAGE_H - 18) y = PAGE_H - 18 - nutH;
  doc.setFillColor(...SAND_BG); doc.roundedRect(M, y, CONTENT_W, nutH, 2, 2, "F");
  doc.setFont("Montserrat", "semibold"); doc.setFontSize(9.5); doc.setTextColor(...NAVY);
  doc.text(nut, M + 4, y + 6);

  doc.setFont("Montserrat", "normal"); doc.setFontSize(7); doc.setTextColor(...MUTED);
  doc.text(`${opts.userName} · Generated by BrainWise${opts.dateTaken ? " · " + opts.dateTaken : ""} · Confidential`, M, PAGE_H - 8);

  doc.save(`${opts.userName.replace(/\s+/g, "_")}_${onePager.audience}_one-page-snapshot.pdf`);
}
