import jsPDF from "jspdf";
import type { OnePagerSection, OnePagerVoice } from "./pairedSectionTypes";

type RGB = [number, number, number];

const NAVY: RGB = [2, 31, 54];
const NAVY_CIRCLE: RGB = [16, 38, 58];
const ORANGE: RGB = [245, 116, 26];
const PEACH: RGB = [251, 224, 200];
const TEAL: RGB = [0, 109, 119];
const GRAY: RGB = [109, 104, 117];
const PURPLE: RGB = [60, 9, 108];
const AMBER: RGB = [255, 183, 3];
const MUSTARD: RGB = [122, 88, 0];
const BLACK: RGB = [30, 30, 30];

const SHARED_LABELS: [keyof OnePagerSection["shared"], string][] = [
  ["strong", "What holds you together"],
  ["talk", "How you two talk"],
  ["fight", "What your fights turn into"],
  ["repair", "How the aftermath goes"],
];

const VOICE_LABELS: [keyof OnePagerVoice, string][] = [
  ["bring", "What I bring us"],
  ["need", "What I need from you"],
  ["talk", "How I show up in a hard talk"],
  ["clash", "What happens to me when we clash"],
  ["repair", "How I find my way back"],
  ["close", "How I feel closest to you"],
];

const txt = (v: { text?: string } | undefined) => (v?.text ?? "").trim();

export interface PairedOnePagerPdfOpts {
  nameA: string;
  nameB: string;
  mode?: string;
  dateGenerated?: string;
  /** Person A / Person B substitution. Never applied to the first-person columns. */
  nm?: (s: string) => string;
  /** Dimension colour for a facet chip, when the facet resolves in the map. */
  facetColor?: (facet: string) => RGB | undefined;
}

export async function generatePairedOnePagerPdf(
  data: OnePagerSection,
  opts: PairedOnePagerPdfOpts,
): Promise<void> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const { registerPdfFonts } = await import("./pdfFonts");
  await registerPdfFonts(doc);

  const nm = opts.nm ?? ((s: string) => s);
  const PAGE_W = doc.internal.pageSize.getWidth();
  const PAGE_H = doc.internal.pageSize.getHeight();
  const M = 14;
  const CONTENT_W = PAGE_W - M * 2;
  const BAND_H = 50;
  const BOTTOM = PAGE_H - 14;

  const logo = await (async () => {
    try {
      const res = await fetch("/logo-orange-white.png");
      if (!res.ok) return null;
      const blob = await res.blob();
      return await new Promise<string>((resolve) => {
        const r = new FileReader();
        r.onloadend = () => resolve(r.result as string);
        r.readAsDataURL(blob);
      });
    } catch {
      return null;
    }
  })();

  const header = (eyebrow: string) => {
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, PAGE_W, BAND_H, "F");
    doc.setFillColor(...NAVY_CIRCLE);
    doc.circle(PAGE_W - 4, 10, 30, "F");
    doc.circle(PAGE_W - 30, 42, 7, "F");
    doc.setDrawColor(...ORANGE);
    doc.setLineWidth(0.8);
    doc.circle(PAGE_W - 60, 20, 11, "S");
    doc.setFillColor(...PEACH);
    doc.circle(PAGE_W - 44, 34, 2.6, "F");

    if (logo) {
      const logoH = 30;
      let logoW = 52;
      try {
        const p = doc.getImageProperties(logo);
        logoW = (p.width / p.height) * logoH;
      } catch { /* fallback width */ }
      doc.addImage(logo, "PNG", M, (BAND_H - logoH) / 2, logoW, logoH, undefined, "FAST");
    } else {
      doc.setFont("Poppins", "extrabold");
      doc.setFontSize(20);
      doc.setTextColor(255, 255, 255);
      doc.text("BrainWise", M, BAND_H / 2 + 3);
    }
    doc.setFont("Montserrat", "semibold");
    doc.setFontSize(9.5);
    doc.setTextColor(...ORANGE);
    doc.setCharSpace(1.1);
    doc.text(eyebrow, PAGE_W - M, BAND_H / 2 + 1, { align: "right" });
    doc.setCharSpace(0);
  };

  const footer = () => {
    doc.setFont("Montserrat", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...GRAY);
    doc.text(
      `${opts.nameA} & ${opts.nameB} · Generated by BrainWise${opts.dateGenerated ? " · " + opts.dateGenerated : ""} · Confidential`,
      M,
      PAGE_H - 8,
    );
  };

  const watch = (data.watch ?? []).filter(Boolean).slice(0, 2);
  const talkAbout = (data.talk_about ?? []).filter(Boolean).slice(0, 4);
  const preview = (data.report_preview ?? []).filter(Boolean);

  /**
   * Page one is a fixed sheet. Everything is laid out through this one function
   * so a dry run can measure the exact height before anything is drawn.
   */
  const layoutPageOne = (step: number, draw: boolean): number => {
    const body = 9 - step * 0.3;
    const lh = 4.1 - step * 0.12;
    let y = BAND_H + 12;

    const heading = (t: string) => {
      y += 3.2;
      if (draw) {
        doc.setFont("Poppins", "bold");
        doc.setFontSize(body + 1.6);
        doc.setTextColor(...NAVY);
        doc.text(t, M, y);
      }
      y += 2;
      if (draw) {
        doc.setDrawColor(...NAVY);
        doc.setLineWidth(0.3);
        doc.line(M, y, M + CONTENT_W, y);
      }
      y += 4;
    };

    /* title */
    doc.setFont("Poppins", "bold");
    doc.setFontSize(body + 6);
    const title = doc.splitTextToSize(nm(data.title ?? ""), CONTENT_W);
    if (draw) {
      doc.setTextColor(...NAVY);
      doc.text(title, M, y);
    }
    y += title.length * (lh + 2.4) + 1;

    /* legend */
    if (draw) {
      doc.setFillColor(...NAVY);
      doc.circle(M + 1.2, y - 1, 1.2, "F");
      doc.setFont("Montserrat", "normal");
      doc.setFontSize(body - 1);
      doc.setTextColor(...GRAY);
      doc.text(opts.nameA, M + 4, y);
      const wA = doc.getTextWidth(opts.nameA);
      doc.setFillColor(...MUSTARD);
      doc.circle(M + 4 + wA + 5.2, y - 1, 1.2, "F");
      doc.text(opts.nameB, M + 4 + wA + 8, y);
    }
    y += lh + 1;

    /* opening */
    const opening = (data.opening ?? "").trim();
    if (opening) {
      doc.setFont("Montserrat", "normal");
      doc.setFontSize(body);
      const lines = doc.splitTextToSize(nm(opening), CONTENT_W - 5);
      const h = lines.length * lh;
      if (draw) {
        doc.setFillColor(...TEAL);
        doc.rect(M, y - lh + 1.2, 1, h, "F");
        doc.setTextColor(...BLACK);
        doc.text(lines, M + 4, y);
      }
      y += h + 1;
    }

    /* shared rows */
    heading("What happens between you");
    const labelW = 44;
    SHARED_LABELS.forEach(([key, label], i) => {
      const t = txt(data.shared?.[key]);
      if (!t) return;
      if (i > 0) {
        if (draw) {
          doc.setDrawColor(220, 224, 228);
          doc.setLineWidth(0.2);
          doc.line(M, y - lh + 1.4, M + CONTENT_W, y - lh + 1.4);
        }
        y += 1.4;
      }
      doc.setFont("Montserrat", "normal");
      doc.setFontSize(body);
      const lines = doc.splitTextToSize(nm(t), CONTENT_W - labelW - 4);
      if (draw) {
        doc.setFont("Poppins", "bold");
        doc.setFontSize(body - 0.4);
        doc.setTextColor(...NAVY);
        doc.text(doc.splitTextToSize(label, labelW - 3), M, y);
        doc.setFont("Montserrat", "normal");
        doc.setFontSize(body);
        doc.setTextColor(...BLACK);
        doc.text(lines, M + labelW, y);
      }
      y += Math.max(lines.length, 1) * lh + 1.4;
    });

    /* first-person columns */
    heading("In your own words, to each other");
    const gutter = 8;
    const colW = (CONTENT_W - gutter) / 2;
    const drawVoice = (
      voice: OnePagerVoice | undefined,
      x: number,
      startY: number,
      color: RGB,
      head: string,
    ): number => {
      let yy = startY;
      const top = yy;
      if (draw) {
        doc.setFont("Poppins", "bold");
        doc.setFontSize(body - 0.6);
        doc.setTextColor(...color);
        doc.text(doc.splitTextToSize(head, colW - 5), x + 4, yy);
      }
      doc.setFont("Poppins", "bold");
      doc.setFontSize(body - 0.6);
      yy += doc.splitTextToSize(head, colW - 5).length * lh + 0.8;
      for (const [key, label] of VOICE_LABELS) {
        const t = txt(voice?.[key]);
        if (!t) continue;
        if (draw) {
          doc.setFont("Montserrat", "semibold");
          doc.setFontSize(body - 2.4);
          doc.setTextColor(...GRAY);
          doc.text(label.toUpperCase(), x + 4, yy, { charSpace: 0.2 });
        }
        yy += lh - 1;
        doc.setFont("Montserrat", "normal");
        doc.setFontSize(body - 0.6);
        // quoted speech: no name substitution here by design
        const lines = doc.splitTextToSize(`“${t}”`, colW - 5);
        if (draw) {
          doc.setTextColor(...NAVY);
          doc.text(lines, x + 4, yy);
        }
        yy += lines.length * (lh - 0.2) + 1.4;
      }
      if (draw) {
        doc.setFillColor(...color);
        doc.rect(x, top - lh + 1.2, 1, yy - top, "F");
      }
      return yy;
    };
    const leftEnd = drawVoice(data.a_to_b, M, y, NAVY, `In ${opts.nameA}'s words, to ${opts.nameB}`);
    const rightEnd = drawVoice(data.b_to_a, M + colW + gutter, y, MUSTARD, `In ${opts.nameB}'s words, to ${opts.nameA}`);
    y = Math.max(leftEnd, rightEnd) + 1;

    /* watch */
    if (watch.length > 0) {
      heading("Keep an eye on");
      let maxY = y;
      watch.forEach((w, i) => {
        const x = i === 0 ? M : M + colW + gutter;
        let yy = y;
        const top = yy;
        doc.setFont("Poppins", "bold");
        doc.setFontSize(body - 0.4);
        const pt = doc.splitTextToSize(nm(w.point ?? ""), colW - 5);
        if (draw) {
          doc.setTextColor(...MUSTARD);
          doc.text(pt, x + 4, yy);
        }
        yy += pt.length * lh;
        doc.setFont("Montserrat", "normal");
        doc.setFontSize(body - 0.5);
        const bd = doc.splitTextToSize(nm(w.body ?? ""), colW - 5);
        if (draw) {
          doc.setTextColor(...BLACK);
          doc.text(bd, x + 4, yy);
        }
        yy += bd.length * (lh - 0.2);
        if (draw) {
          doc.setFillColor(...AMBER);
          doc.rect(x, top - lh + 1.2, 1, yy - top, "F");
        }
        maxY = Math.max(maxY, yy);
      });
      y = maxY + 1;
    }

    /* talk about */
    if (talkAbout.length > 0) {
      heading("Talk about this together");
      let rowY = y;
      let rowMax = y;
      talkAbout.forEach((t, i) => {
        const x = i % 2 === 0 ? M : M + colW + gutter;
        if (i % 2 === 0 && i > 0) {
          rowY = rowMax + 1.6;
          rowMax = rowY;
        }
        doc.setFont("Montserrat", "normal");
        doc.setFontSize(body - 0.5);
        const lines = doc.splitTextToSize(nm(t), colW - 8);
        if (draw) {
          doc.setFillColor(...PURPLE);
          doc.circle(x + 2.2, rowY - 1.1, 2.2, "F");
          doc.setFont("Poppins", "bold");
          doc.setFontSize(body - 2.4);
          doc.setTextColor(255, 255, 255);
          doc.text(String(i + 1), x + 2.2, rowY - 0.2, { align: "center" });
          doc.setFont("Montserrat", "normal");
          doc.setFontSize(body - 0.5);
          doc.setTextColor(...BLACK);
          doc.text(lines, x + 6.4, rowY);
        }
        rowMax = Math.max(rowMax, rowY + lines.length * (lh - 0.2));
      });
      y = rowMax + 1;
    }

    /* disclaimer */
    const disc = (data.disclaimer ?? "").trim();
    if (disc) {
      y += 2;
      if (draw) {
        doc.setDrawColor(220, 224, 228);
        doc.setLineWidth(0.2);
        doc.line(M, y, M + CONTENT_W, y);
      }
      y += 3.4;
      doc.setFont("Montserrat", "normal");
      doc.setFontSize(6.6);
      const lines = doc.splitTextToSize(nm(disc), CONTENT_W);
      if (draw) {
        doc.setTextColor(...GRAY);
        doc.text(lines, M, y);
      }
      y += lines.length * 3;
    }

    return y;
  };

  /* measure, then draw at the first step that fits */
  let step = 0;
  let end = layoutPageOne(0, false);
  while (end > BOTTOM && step < 3) {
    step += 1;
    end = layoutPageOne(step, false);
  }
  if (end > BOTTOM) {
    console.warn(
      `[paired one-pager] page one overflows by ${(end - BOTTOM).toFixed(1)}mm at the smallest step; the generator's word caps need revisiting.`,
    );
  }
  header("PAIRED SNAPSHOT");
  layoutPageOne(step, true);
  footer();

  /* ---------- page two ---------- */
  if (preview.length > 0) {
    doc.addPage();
    header("YOUR FULL REPORT");
    let y = BAND_H + 12;
    doc.setFont("Poppins", "bold");
    doc.setFontSize(15);
    doc.setTextColor(...NAVY);
    doc.text("What is in your full report", M, y);
    y += 7;
    doc.setFont("Montserrat", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...GRAY);
    const lead = doc.splitTextToSize(
      "Page one is the short version. Your full report goes deeper on each of these, with the patterns behind them mapped question by question.",
      CONTENT_W,
    );
    doc.text(lead, M, y);
    y += lead.length * 4.4 + 4;

    const gutter = 8;
    const colW = (CONTENT_W - gutter) / 2;
    let rowY = y;
    let rowMax = y;
    preview.forEach((p, i) => {
      const x = i % 2 === 0 ? M : M + colW + gutter;
      if (i % 2 === 0 && i > 0) {
        rowY = rowMax + 4;
        rowMax = rowY;
      }
      const top = rowY;
      let yy = rowY;
      doc.setFont("Poppins", "extrabold");
      doc.setFontSize(13);
      if (i % 2 === 0 || true) {
        doc.setTextColor(...TEAL);
        doc.text(String(i + 1), x + 4, yy + 0.6);
      }
      doc.setFont("Poppins", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(...NAVY);
      const head = doc.splitTextToSize(nm(p.heading || p.section || ""), colW - 14);
      doc.text(head, x + 12, yy);
      yy += Math.max(head.length * 4.4, 5);
      doc.setFont("Montserrat", "normal");
      doc.setFontSize(8.6);
      doc.setTextColor(...BLACK);
      const body = doc.splitTextToSize(nm(p.text ?? ""), colW - 5);
      doc.text(body, x + 4, yy);
      yy += body.length * 3.9 + 1.5;

      /* facet chips — page two only */
      const facets = Array.isArray(p.facets) ? p.facets.filter(Boolean) : [];
      if (facets.length > 0) {
        let cx = x + 4;
        doc.setFont("Montserrat", "semibold");
        doc.setFontSize(6.6);
        for (const f of facets) {
          const label = nm(f);
          const w = doc.getTextWidth(label) + 4;
          if (cx + w > x + colW - 1) {
            cx = x + 4;
            yy += 5;
          }
          const c = opts.facetColor?.(f) ?? GRAY;
          doc.setFillColor(c[0], c[1], c[2]);
          doc.setDrawColor(c[0], c[1], c[2]);
          doc.setLineWidth(0.2);
          doc.saveGraphicsState();
          // @ts-expect-error jsPDF GState typing
          doc.setGState(new (doc as any).GState({ opacity: 0.12 }));
          doc.roundedRect(cx, yy - 3, w, 4.4, 2.2, 2.2, "F");
          doc.restoreGraphicsState();
          doc.roundedRect(cx, yy - 3, w, 4.4, 2.2, 2.2, "S");
          doc.setTextColor(c === AMBER ? MUSTARD[0] : c[0], c === AMBER ? MUSTARD[1] : c[1], c === AMBER ? MUSTARD[2] : c[2]);
          doc.text(label, cx + 2, yy);
          cx += w + 2;
        }
        yy += 3;
      }

      doc.setFillColor(...TEAL);
      doc.rect(x, top - 4, 1, Math.max(yy - top + 2, 6), "F");
      rowMax = Math.max(rowMax, yy);
    });
    footer();
  }

  const file = `${opts.nameA}_and_${opts.nameB}_paired-snapshot.pdf`.replace(/\s+/g, "_");
  doc.save(file);
}
