// Self-contained jsPDF primitives for Team & Paired PDF exports.
// Intentionally duplicated from generateResultsPdf.ts so the individual PTP/NAI/AIRSA
// exports can never regress from changes made here.
import jsPDF from "jspdf";

export const PAGE_W = 210;
export const PAGE_H = 297;
export const MARGIN_L = 15;
export const MARGIN_R = 15;
export const MARGIN_T = 20;
export const MARGIN_B = 25;
export const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;
export const FOOTER_Y = PAGE_H - 12;
export const MIN_BLOCK_SPACE = 30;

export const NAVY = [2, 31, 54] as const;
export const MUTED = [109, 104, 117] as const;
export const BLACK = [30, 30, 30] as const;
export const SAND_BG = [249, 247, 241] as const;
export const ORANGE = [245, 116, 26] as const;
export const TEAL = [0, 109, 119] as const;
export const GRAY = [109, 104, 117] as const;
export const PURPLE = [60, 9, 108] as const;
export const GREEN = [45, 106, 79] as const;
export const MUSTARD = [122, 88, 0] as const;
export const AMBER = [255, 183, 3] as const;

const NAVY_CIRCLE = [16, 38, 58] as const;
const SAND_CIRCLE = [251, 224, 200] as const;
const DISCLAIMER_ICON_BG = [255, 230, 210] as const;

export function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

export function cleanMarkdown(text: string): string {
  return (text ?? "").replace(/\*\*(.+?)\*\*/g, "$1").replace(/\*(.+?)\*/g, "$1");
}

export function splitParas(text: string): string[] {
  const s = (text ?? "").trim();
  if (!s) return [];
  if (/\n{2,}/.test(s)) return s.split(/\n{2,}/).map((p) => p.trim()).filter(Boolean);
  const sentences =
    s.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g)?.map((x) => x.trim()).filter(Boolean) ?? [s];
  if (sentences.length < 2) return [s];
  const mid = Math.ceil(sentences.length / 2);
  return [sentences.slice(0, mid).join(" "), sentences.slice(mid).join(" ")];
}

export interface PdfContext {
  doc: jsPDF;
  y: number;
  addFooter: () => void;
  renderContinuationHeader: () => void;
  checkPageBreak: (needed: number) => void;
  ensureBlockSpace: (needed?: number) => void;
  reserveBlockOrAllow: (totalH: number) => void;
  sectionHeading: (title: string, firstContentHeight?: number) => void;
  bodyText: (text: string, indent?: number) => void;
  setCurrentSection: (title: string) => void;
}

export function createPdfContext(doc: jsPDF): PdfContext {
  const state = { y: MARGIN_T, currentSectionTitle: "" };
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const addFooter = () => {
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.setFont("Montserrat", "normal");
    doc.text(
      `Generated by BrainWise | ${today} | Confidential`,
      PAGE_W / 2,
      FOOTER_Y,
      { align: "center" },
    );
    doc.setDrawColor(220, 220, 220);
    doc.line(MARGIN_L, FOOTER_Y - 3, PAGE_W - MARGIN_R, FOOTER_Y - 3);
  };

  const renderContinuationHeader = () => {
    if (state.currentSectionTitle === "") return;
    doc.setFontSize(7.5);
    doc.setFont("Montserrat", "normal");
    doc.setTextColor(...MUTED);
    doc.text(
      `${state.currentSectionTitle.toUpperCase()} · CONTINUED`,
      MARGIN_L,
      MARGIN_T - 5,
    );
  };

  const checkPageBreak = (needed: number) => {
    if (state.y + needed > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      state.y = MARGIN_T;
      renderContinuationHeader();
    }
  };

  const ensureBlockSpace = (needed: number = MIN_BLOCK_SPACE) => {
    if (state.y + needed > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      state.y = MARGIN_T;
      renderContinuationHeader();
    }
  };

  const PAGE_AVAIL = PAGE_H - MARGIN_T - MARGIN_B;
  const reserveBlockOrAllow = (totalH: number) => {
    if (totalH <= PAGE_AVAIL && state.y + totalH > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      state.y = MARGIN_T;
      renderContinuationHeader();
    }
  };

  const atTopOfPage = () => state.y <= MARGIN_T + 5;

  const sectionHeading = (title: string, firstContentHeight?: number) => {
    state.currentSectionTitle = "";
    const headingBlockH = 10;
    const reserveH =
      firstContentHeight != null
        ? Math.max(MIN_BLOCK_SPACE, headingBlockH + firstContentHeight)
        : MIN_BLOCK_SPACE;
    ensureBlockSpace(reserveH);
    state.currentSectionTitle = title;
    if (!atTopOfPage()) state.y += 4;
    doc.setFontSize(13);
    doc.setTextColor(...NAVY);
    doc.setFont("Poppins", "bold");
    doc.text(title, MARGIN_L, state.y);
    state.y += 2;
    doc.setDrawColor(...NAVY);
    doc.setLineWidth(0.5);
    doc.line(MARGIN_L, state.y, MARGIN_L + CONTENT_W, state.y);
    state.y += 6;
  };

  const bodyText = (text: string, indent = 0) => {
    doc.setFontSize(9);
    doc.setFont("Montserrat", "normal");
    doc.setTextColor(...BLACK);
    const lines = doc.splitTextToSize(cleanMarkdown(text), CONTENT_W - indent);
    if (lines.length > 1) ensureBlockSpace(Math.min(MIN_BLOCK_SPACE, lines.length * 4.5 + 4));
    for (const line of lines) {
      checkPageBreak(5);
      doc.text(line, MARGIN_L + indent, state.y);
      state.y += 4.5;
    }
  };

  return {
    doc,
    get y() {
      return state.y;
    },
    set y(v: number) {
      state.y = v;
    },
    addFooter,
    renderContinuationHeader,
    checkPageBreak,
    ensureBlockSpace,
    reserveBlockOrAllow,
    sectionHeading,
    bodyText,
    setCurrentSection: (t: string) => {
      state.currentSectionTitle = t;
    },
  } as PdfContext;
}

export interface CoverField {
  label: string;
  value: string;
}

export interface CoverParams {
  eyebrow: string;
  titleLine1: string;
  titleLine2?: string;
  trademark?: boolean;
  subtitle: string;
  contextPillLabel: string;
  field1: CoverField;
  field2: CoverField;
  field3?: CoverField;
  disclaimer: string;
  copyright: string;
}

export async function renderCoverPage(doc: jsPDF, p: CoverParams): Promise<void> {
  const logoDataUrl = await (async () => {
    try {
      const res = await fetch("/logo-orange-white.png");
      if (!res.ok) return null;
      const blob = await res.blob();
      return await new Promise<string>((resolve, reject) => {
        const r = new FileReader();
        r.onloadend = () => resolve(r.result as string);
        r.onerror = reject;
        r.readAsDataURL(blob);
      });
    } catch {
      return null;
    }
  })();

  const NAVY_BLOCK_H = 150;
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, PAGE_W, NAVY_BLOCK_H, "F");

  doc.setFillColor(...NAVY_CIRCLE);
  doc.circle(195, 25, 28, "F");
  doc.circle(220, 80, 22, "F");
  doc.circle(165, 45, 10, "F");
  doc.circle(200, 130, 18, "F");
  doc.circle(140, 15, 8, "F");
  doc.circle(175, 105, 6, "F");

  if (logoDataUrl) {
    doc.addImage(logoDataUrl, "PNG", MARGIN_L, 18, 50, 0, undefined, "FAST");
  } else {
    doc.setFont("Poppins", "extrabold");
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.text("BrainWise Enterprises", MARGIN_L, 35);
  }

  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(10);
  doc.setTextColor(...ORANGE);
  doc.setCharSpace(1.5);
  doc.text(p.eyebrow.toUpperCase(), MARGIN_L, 72);
  doc.setCharSpace(0);

  doc.setFont("Poppins", "extrabold");
  doc.setFontSize(36);
  doc.setTextColor(255, 255, 255);
  doc.text(p.titleLine1, MARGIN_L, 88);
  const lastLine = p.titleLine2 ?? p.titleLine1;
  const lastLineY = p.titleLine2 ? 105 : 88;
  if (p.titleLine2) {
    doc.text(p.titleLine2, MARGIN_L, 105);
  }
  if (p.trademark) {
    const lastW = doc.getTextWidth(lastLine);
    const lastX = MARGIN_L + (p.titleLine2 ? 0 : 0);
    doc.setTextColor(...ORANGE);
    doc.setFontSize(20);
    doc.text("™", lastX + lastW + 1, lastLineY - 7);
    doc.setTextColor(255, 255, 255);
  }

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(10);
  doc.setTextColor(220, 230, 240);
  const descLines = doc.splitTextToSize(p.subtitle, CONTENT_W - 60);
  doc.text(descLines, MARGIN_L, 120);

  const pillText = p.contextPillLabel.toUpperCase();
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(9);
  const pillTextWidth = doc.getTextWidth(pillText);
  const pillW = pillTextWidth + 18;
  const pillH = 9;
  const pillY = 138;
  doc.setDrawColor(...ORANGE);
  doc.setLineWidth(0.5);
  doc.setFillColor(...NAVY);
  doc.roundedRect(MARGIN_L, pillY, pillW, pillH, pillH / 2, pillH / 2, "FD");
  doc.setFillColor(...ORANGE);
  doc.circle(MARGIN_L + 5, pillY + pillH / 2, 1.3, "F");
  doc.setTextColor(...ORANGE);
  doc.text(pillText, MARGIN_L + 10, pillY + pillH / 2 + 1.2);

  doc.setFillColor(...SAND_BG);
  doc.rect(0, NAVY_BLOCK_H, PAGE_W, PAGE_H - NAVY_BLOCK_H, "F");

  doc.setFillColor(...SAND_CIRCLE);
  doc.circle(-5, 175, 22, "F");
  doc.circle(15, 235, 16, "F");
  doc.circle(40, 200, 8, "F");
  doc.circle(8, 270, 12, "F");
  doc.circle(60, 250, 6, "F");

  const fieldY = NAVY_BLOCK_H + 14;
  const fieldColW = (CONTENT_W - 10) / 2;

  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(8);
  doc.setTextColor(...ORANGE);
  doc.setCharSpace(1);
  doc.text(p.field1.label.toUpperCase(), MARGIN_L, fieldY);
  doc.text(p.field2.label.toUpperCase(), MARGIN_L + fieldColW + 10, fieldY);
  doc.setCharSpace(0);

  doc.setFont("Poppins", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...NAVY);
  doc.text(p.field1.value, MARGIN_L, fieldY + 9);
  doc.text(p.field2.value, MARGIN_L + fieldColW + 10, fieldY + 9);

  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_L, fieldY + 13, MARGIN_L + fieldColW, fieldY + 13);
  doc.line(MARGIN_L + fieldColW + 10, fieldY + 13, MARGIN_L + CONTENT_W, fieldY + 13);

  let nextY = fieldY + 28;
  if (p.field3) {
    doc.setFont("Montserrat", "semibold");
    doc.setFontSize(8);
    doc.setTextColor(...ORANGE);
    doc.setCharSpace(1);
    doc.text(p.field3.label.toUpperCase(), MARGIN_L, nextY);
    doc.setCharSpace(0);

    doc.setFont("Poppins", "normal");
    doc.setFontSize(13);
    doc.setTextColor(...NAVY);
    doc.text(p.field3.value, MARGIN_L, nextY + 9);
    doc.setDrawColor(180, 180, 180);
    doc.setLineWidth(0.3);
    doc.line(MARGIN_L, nextY + 13, MARGIN_L + CONTENT_W, nextY + 13);
    nextY = nextY + 28;
  }

  const disclaimerY = nextY;
  doc.setFont("Montserrat", "normal");
  doc.setFontSize(9);
  const disclaimerLines = doc.splitTextToSize(p.disclaimer, CONTENT_W - 20);
  const disclaimerH = disclaimerLines.length * 4.5 + 18;

  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(225, 220, 210);
  doc.setLineWidth(0.3);
  doc.roundedRect(MARGIN_L, disclaimerY, CONTENT_W, disclaimerH, 3, 3, "FD");

  doc.setFillColor(...DISCLAIMER_ICON_BG);
  doc.circle(MARGIN_L + 9, disclaimerY + 9, 4, "F");
  doc.setFont("Poppins", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...ORANGE);
  doc.text("i", MARGIN_L + 9, disclaimerY + 10.5, { align: "center" });

  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(9);
  doc.setTextColor(...NAVY);
  doc.setCharSpace(0.5);
  doc.text("IMPORTANT - PLEASE READ", MARGIN_L + 16, disclaimerY + 10);
  doc.setCharSpace(0);

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(60, 60, 60);
  doc.text(disclaimerLines, MARGIN_L + 6, disclaimerY + 18);

  const footerCoverY = PAGE_H - 22;
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(8);
  doc.setTextColor(...NAVY);
  doc.setCharSpace(0.8);
  doc.text("GENERATED BY BRAINWISE ENTERPRISES, LLC", MARGIN_L, footerCoverY);
  doc.setCharSpace(0);

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  const dateRight = new Date()
    .toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
    .toUpperCase();
  doc.text(dateRight, PAGE_W - MARGIN_R, footerCoverY, { align: "right" });

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(7);
  doc.setTextColor(140, 140, 140);
  const copyText = p.copyright.replace(/\{year\}/g, String(new Date().getFullYear()));
  const copyLines = doc.splitTextToSize(copyText, CONTENT_W);
  doc.text(copyLines, MARGIN_L, footerCoverY + 5);
}

export function stampPageNumbers(doc: jsPDF): void {
  const totalPages = doc.getNumberOfPages();
  const contentTotalPages = totalPages - 1;
  for (let p = 2; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(7);
    doc.setFont("Montserrat", "normal");
    doc.setTextColor(...MUTED);
    doc.text(
      `Page ${p - 1} of ${contentTotalPages}`,
      PAGE_W - MARGIN_R,
      FOOTER_Y,
      { align: "right" },
    );
  }
}

// ─── Distribution row helpers ───────────────────────────────────────────────

const ROW_LABEL_FONT = 8.5;
const ROW_LEFT_LABEL_W = 70;
const AXIS_LEFT_PAD = 2;
const AXIS_RIGHT_PAD = 2;

function drawAxis(
  ctx: PdfContext,
  axisY: number,
  axisX: number,
  axisW: number,
): void {
  const { doc } = ctx;
  doc.setDrawColor(210, 210, 210);
  doc.setLineWidth(0.2);
  doc.line(axisX, axisY, axisX + axisW, axisY);
  // 0/50/100 ticks
  doc.setDrawColor(220, 220, 220);
  [0, 50, 100].forEach((v) => {
    const x = axisX + (v / 100) * axisW;
    doc.line(x, axisY - 0.8, x, axisY + 0.8);
  });
}

export function drawPairDistRow(
  ctx: PdfContext,
  args: { label: string; a: number | null | undefined; b: number | null | undefined },
): void {
  const rowH = 10;
  ctx.checkPageBreak(rowH + 2);
  const { doc } = ctx;
  const y = ctx.y;
  const aVal = typeof args.a === "number" ? Math.max(0, Math.min(100, args.a)) : null;
  const bVal = typeof args.b === "number" ? Math.max(0, Math.min(100, args.b)) : null;

  // Label + gap on same line above axis
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(ROW_LABEL_FONT);
  doc.setTextColor(...NAVY);
  const labelLines = doc.splitTextToSize(cleanMarkdown(args.label), CONTENT_W - 30);
  doc.text(labelLines[0], MARGIN_L, y + 3);

  if (aVal != null && bVal != null) {
    const gap = Math.abs(aVal - bVal).toFixed(0);
    doc.setFont("Montserrat", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(`gap ${gap}`, MARGIN_L + CONTENT_W, y + 3, { align: "right" });
  }

  const axisY = y + 7.5;
  const axisX = MARGIN_L + AXIS_LEFT_PAD;
  const axisW = CONTENT_W - AXIS_LEFT_PAD - AXIS_RIGHT_PAD;
  drawAxis(ctx, axisY, axisX, axisW);

  if (aVal != null && bVal != null) {
    const ax = axisX + (aVal / 100) * axisW;
    const bx = axisX + (bVal / 100) * axisW;
    doc.setDrawColor(120, 120, 120);
    doc.setLineWidth(0.6);
    doc.line(Math.min(ax, bx), axisY, Math.max(ax, bx), axisY);
  }
  if (aVal != null) {
    const ax = axisX + (aVal / 100) * axisW;
    doc.setFillColor(...NAVY);
    doc.circle(ax, axisY, 1.6, "F");
  }
  if (bVal != null) {
    const bx = axisX + (bVal / 100) * axisW;
    doc.setFillColor(...MUSTARD);
    doc.circle(bx, axisY, 1.6, "F");
  }

  ctx.y = y + rowH + 1;
}

export function drawTeamDistRow(
  ctx: PdfContext,
  args: { label: string; scores: number[]; dotColor?: readonly [number, number, number] },
): void {
  const { doc } = ctx;
  const scores = Array.isArray(args.scores) ? args.scores.filter((n) => typeof n === "number") : [];

  if (scores.length === 0) {
    // Plain text row fallback
    const rowH = 6;
    ctx.checkPageBreak(rowH + 1);
    doc.setFont("Montserrat", "normal");
    doc.setFontSize(ROW_LABEL_FONT);
    doc.setTextColor(...BLACK);
    doc.text(cleanMarkdown(args.label), MARGIN_L, ctx.y + 4);
    ctx.y += rowH;
    return;
  }

  const rowH = 12;
  ctx.checkPageBreak(rowH + 2);
  const y = ctx.y;

  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(ROW_LABEL_FONT);
  doc.setTextColor(...NAVY);
  const labelLines = doc.splitTextToSize(cleanMarkdown(args.label), CONTENT_W - 30);
  doc.text(labelLines[0], MARGIN_L, y + 3);

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(`n=${scores.length}`, MARGIN_L + CONTENT_W, y + 3, { align: "right" });

  const axisY = y + 8;
  const axisX = MARGIN_L + AXIS_LEFT_PAD;
  const axisW = CONTENT_W - AXIS_LEFT_PAD - AXIS_RIGHT_PAD;
  drawAxis(ctx, axisY, axisX, axisW);

  const dotColor = args.dotColor ?? TEAL;
  const jitter = [-1.8, 0, 1.8];
  doc.setFillColor(dotColor[0], dotColor[1], dotColor[2]);
  scores.forEach((s, i) => {
    const v = Math.max(0, Math.min(100, s));
    const x = axisX + (v / 100) * axisW;
    const dy = jitter[i % 3];
    doc.circle(x, axisY + dy, 1.3, "F");
  });

  const mean = scores.reduce((a, b) => a + b, 0) / scores.length;
  const mx = axisX + (mean / 100) * axisW;
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.9);
  doc.line(mx, axisY - 3, mx, axisY + 3);

  ctx.y = y + rowH + 1;
}
