// Self-contained jsPDF primitives for Team & Paired PDF exports.
// Intentionally duplicated from generateResultsPdf.ts so the individual PTP/NAI/AIRSA
// exports can never regress from changes made here.
import jsPDF from "jspdf";
import {
  bulletFacets,
  bulletToText,
  isBulletObject,
  isMoveBullet,
  stripMovePrefix,
  normFacetName,
  facetDisplayLabel,
  type Bullet,
} from "./pairedSectionTypes";

export const PAGE_W = 210;
export const PAGE_H = 297;
export const MARGIN_L = 15;
export const MARGIN_R = 15;
export const MARGIN_T = 20;
export const MARGIN_B = 25;
export const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;
export const FOOTER_Y = PAGE_H - 12;
export const MIN_BLOCK_SPACE = 30;

export const NAVY = [2, 31, 54] as const;
export const MUTED = [109, 104, 117] as const;
export const BLACK = [30, 30, 30] as const;
export const SAND_BG = [249, 247, 241] as const;
export const ORANGE = [245, 116, 26] as const;
export const TEAL = [0, 109, 119] as const;
export const GRAY = [109, 104, 117] as const;
export const PURPLE = [60, 9, 108] as const;
export const GREEN = [45, 106, 79] as const;
export const MUSTARD = [122, 88, 0] as const;
export const AMBER = [255, 183, 3] as const;

export const NAVY_CIRCLE = [16, 38, 58] as const;
export const SAND_CIRCLE = [251, 224, 200] as const;
const DISCLAIMER_ICON_BG = [255, 230, 210] as const;

export function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [
    parseInt(h.substring(0, 2), 16),
    parseInt(h.substring(2, 4), 16),
    parseInt(h.substring(4, 6), 16),
  ];
}

export function cleanMarkdown(text: string): string {
  return (text ?? "").replace(/\*\*(.+?)\*\*/g, "$1").replace(/\*(.+?)\*/g, "$1");
}

export function splitParas(text: string): string[] {
  const s = (text ?? "").trim();
  if (!s) return [];
  if (/\n{2,}/.test(s)) return s.split(/\n{2,}/).map((p) => p.trim()).filter(Boolean);
  const sentences =
    s.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g)?.map((x) => x.trim()).filter(Boolean) ?? [s];
  if (sentences.length < 2) return [s];
  const mid = Math.ceil(sentences.length / 2);
  return [sentences.slice(0, mid).join(" "), sentences.slice(mid).join(" ")];
}

export interface PdfContext {
  doc: jsPDF;
  y: number;
  addFooter: () => void;
  renderContinuationHeader: () => void;
  checkPageBreak: (needed: number) => void;
  ensureBlockSpace: (needed?: number) => void;
  reserveBlockOrAllow: (totalH: number) => void;
  sectionHeading: (title: string, firstContentHeight?: number, eyebrow?: string) => void;
  bodyText: (text: string, indent?: number) => void;
  setCurrentSection: (title: string) => void;
}

export function createPdfContext(doc: jsPDF): PdfContext {
  const state = { y: MARGIN_T, currentSectionTitle: "" };
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const addFooter = () => {
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.setFont("Montserrat", "normal");
    doc.text(
      `Generated by BrainWise | ${today} | Confidential`,
      PAGE_W / 2,
      FOOTER_Y,
      { align: "center" },
    );
    doc.setDrawColor(220, 220, 220);
    doc.line(MARGIN_L, FOOTER_Y - 3, PAGE_W - MARGIN_R, FOOTER_Y - 3);
  };

  const renderContinuationHeader = () => {
    if (state.currentSectionTitle === "") return;
    doc.setFontSize(7.5);
    doc.setFont("Montserrat", "normal");
    doc.setTextColor(...MUTED);
    doc.text(
      `${state.currentSectionTitle.toUpperCase()} · CONTINUED`,
      MARGIN_L,
      MARGIN_T - 5,
    );
  };

  const checkPageBreak = (needed: number) => {
    if (state.y + needed > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      state.y = MARGIN_T;
      renderContinuationHeader();
    }
  };

  const ensureBlockSpace = (needed: number = MIN_BLOCK_SPACE) => {
    if (state.y + needed > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      state.y = MARGIN_T;
      renderContinuationHeader();
    }
  };

  const PAGE_AVAIL = PAGE_H - MARGIN_T - MARGIN_B;
  const reserveBlockOrAllow = (totalH: number) => {
    if (totalH <= PAGE_AVAIL && state.y + totalH > PAGE_H - MARGIN_B) {
      addFooter();
      doc.addPage();
      state.y = MARGIN_T;
      renderContinuationHeader();
    }
  };

  const atTopOfPage = () => state.y <= MARGIN_T + 5;

  const sectionHeading = (title: string, firstContentHeight?: number, eyebrow?: string) => {
    state.currentSectionTitle = "";
    // 3.5mm of clear space between the eyebrow baseline and the 13pt heading's
    // cap height (~3.3mm above its baseline), so the eyebrow reads as its own line.
    const eyebrowH = eyebrow ? 6.8 : 0;
    const headingBlockH = 10 + eyebrowH;
    const reserveH =
      firstContentHeight != null
        ? Math.max(MIN_BLOCK_SPACE, headingBlockH + firstContentHeight)
        : MIN_BLOCK_SPACE;
    ensureBlockSpace(reserveH);
    state.currentSectionTitle = title;
    if (!atTopOfPage()) state.y += 4;
    if (eyebrow) {
      doc.setFont("Poppins", "bold");
      doc.setFontSize(7);
      doc.setTextColor(...ORANGE);
      // Draw glyph by glyph: jsPDF's charSpace also pads after the final glyph,
      // which rendered as a stray trailing mark on every eyebrow.
      let ex = MARGIN_L;
      const label = eyebrow.trim().toUpperCase();
      for (let i = 0; i < label.length; i++) {
        const ch = label[i];
        doc.text(ch, ex, state.y);
        ex += doc.getTextWidth(ch) + 0.6;
      }
      state.y += 6.8;
    }
    doc.setFontSize(13);
    doc.setTextColor(...NAVY);
    doc.setFont("Poppins", "bold");
    doc.text(title, MARGIN_L, state.y);
    state.y += 2;
    doc.setDrawColor(...NAVY);
    doc.setLineWidth(0.5);
    doc.line(MARGIN_L, state.y, MARGIN_L + CONTENT_W, state.y);
    state.y += 6;
  };

  const bodyText = (text: string, indent = 0) => {
    doc.setFontSize(9);
    doc.setFont("Montserrat", "normal");
    doc.setTextColor(...BLACK);
    const lines = doc.splitTextToSize(cleanMarkdown(text), CONTENT_W - indent);
    if (lines.length > 1) ensureBlockSpace(Math.min(MIN_BLOCK_SPACE, lines.length * 4.5 + 4));
    for (const line of lines) {
      checkPageBreak(5);
      doc.text(line, MARGIN_L + indent, state.y);
      state.y += 4.5;
    }
  };

  return {
    doc,
    get y() {
      return state.y;
    },
    set y(v: number) {
      state.y = v;
    },
    addFooter,
    renderContinuationHeader,
    checkPageBreak,
    ensureBlockSpace,
    reserveBlockOrAllow,
    sectionHeading,
    bodyText,
    setCurrentSection: (t: string) => {
      state.currentSectionTitle = t;
    },
  } as PdfContext;
}

export interface CoverField {
  label: string;
  value: string;
}

export interface CoverParams {
  eyebrow: string;
  titleLine1: string;
  titleLine2?: string;
  trademark?: boolean;
  subtitle: string;
  contextPillLabel: string;
  field1: CoverField;
  field2?: CoverField;
  field3?: CoverField;
  disclaimer: string;
  copyright: string;
}

export async function renderCoverPage(doc: jsPDF, p: CoverParams): Promise<void> {
  const logoDataUrl = await (async () => {
    try {
      const res = await fetch("/logo-orange-white.png");
      if (!res.ok) return null;
      const blob = await res.blob();
      return await new Promise<string>((resolve, reject) => {
        const r = new FileReader();
        r.onloadend = () => resolve(r.result as string);
        r.onerror = reject;
        r.readAsDataURL(blob);
      });
    } catch {
      return null;
    }
  })();

  const NAVY_BLOCK_H = 150;
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, PAGE_W, NAVY_BLOCK_H, "F");

  doc.setFillColor(...NAVY_CIRCLE);
  doc.circle(195, 25, 28, "F");
  doc.circle(220, 80, 22, "F");
  doc.circle(165, 45, 10, "F");
  doc.circle(200, 130, 18, "F");
  doc.circle(140, 15, 8, "F");
  doc.circle(175, 105, 6, "F");

  if (logoDataUrl) {
    doc.addImage(logoDataUrl, "PNG", MARGIN_L, 18, 50, 0, undefined, "FAST");
  } else {
    doc.setFont("Poppins", "extrabold");
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.text("BrainWise Enterprises", MARGIN_L, 35);
  }

  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(10);
  doc.setTextColor(...ORANGE);
  doc.setCharSpace(1.5);
  doc.text(p.eyebrow.toUpperCase(), MARGIN_L, 72);
  doc.setCharSpace(0);

  doc.setFont("Poppins", "extrabold");
  doc.setFontSize(36);
  doc.setTextColor(255, 255, 255);
  doc.text(p.titleLine1, MARGIN_L, 88);
  const lastLine = p.titleLine2 ?? p.titleLine1;
  const lastLineY = p.titleLine2 ? 105 : 88;
  if (p.titleLine2) {
    doc.text(p.titleLine2, MARGIN_L, 105);
  }
  if (p.trademark) {
    const lastW = doc.getTextWidth(lastLine);
    const lastX = MARGIN_L + (p.titleLine2 ? 0 : 0);
    doc.setTextColor(...ORANGE);
    doc.setFontSize(20);
    doc.text("™", lastX + lastW + 1, lastLineY - 7);
    doc.setTextColor(255, 255, 255);
  }

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(10);
  doc.setTextColor(220, 230, 240);
  const descLines = doc.splitTextToSize(p.subtitle, CONTENT_W - 60);
  doc.text(descLines, MARGIN_L, 120);

  const pillText = p.contextPillLabel.toUpperCase();
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(9);
  const pillTextWidth = doc.getTextWidth(pillText);
  const pillW = pillTextWidth + 18;
  const pillH = 9;
  const pillY = 138;
  doc.setDrawColor(...ORANGE);
  doc.setLineWidth(0.5);
  doc.setFillColor(...NAVY);
  doc.roundedRect(MARGIN_L, pillY, pillW, pillH, pillH / 2, pillH / 2, "FD");
  doc.setFillColor(...ORANGE);
  doc.circle(MARGIN_L + 5, pillY + pillH / 2, 1.3, "F");
  doc.setTextColor(...ORANGE);
  doc.text(pillText, MARGIN_L + 10, pillY + pillH / 2 + 1.2);

  doc.setFillColor(...SAND_BG);
  doc.rect(0, NAVY_BLOCK_H, PAGE_W, PAGE_H - NAVY_BLOCK_H, "F");

  doc.setFillColor(...SAND_CIRCLE);
  doc.circle(-5, 175, 22, "F");
  doc.circle(15, 235, 16, "F");
  doc.circle(40, 200, 8, "F");
  doc.circle(8, 270, 12, "F");
  doc.circle(60, 250, 6, "F");

  const fieldY = NAVY_BLOCK_H + 14;
  const fieldColW = (CONTENT_W - 10) / 2;

  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(8);
  doc.setTextColor(...ORANGE);
  doc.setCharSpace(1);
  doc.text(p.field1.label.toUpperCase(), MARGIN_L, fieldY);
  if (p.field2) doc.text(p.field2.label.toUpperCase(), MARGIN_L + fieldColW + 10, fieldY);
  doc.setCharSpace(0);

  doc.setFont("Poppins", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...NAVY);
  doc.text(p.field1.value, MARGIN_L, fieldY + 9);
  if (p.field2) doc.text(p.field2.value, MARGIN_L + fieldColW + 10, fieldY + 9);

  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_L, fieldY + 13, MARGIN_L + fieldColW, fieldY + 13);
  if (p.field2) doc.line(MARGIN_L + fieldColW + 10, fieldY + 13, MARGIN_L + CONTENT_W, fieldY + 13);

  let nextY = fieldY + 28;
  if (p.field3) {
    doc.setFont("Montserrat", "semibold");
    doc.setFontSize(8);
    doc.setTextColor(...ORANGE);
    doc.setCharSpace(1);
    doc.text(p.field3.label.toUpperCase(), MARGIN_L, nextY);
    doc.setCharSpace(0);

    doc.setFont("Poppins", "normal");
    doc.setFontSize(13);
    doc.setTextColor(...NAVY);
    doc.text(p.field3.value, MARGIN_L, nextY + 9);
    doc.setDrawColor(180, 180, 180);
    doc.setLineWidth(0.3);
    doc.line(MARGIN_L, nextY + 13, MARGIN_L + CONTENT_W, nextY + 13);
    nextY = nextY + 28;
  }

  const disclaimerY = nextY;
  doc.setFont("Montserrat", "normal");
  doc.setFontSize(9);
  const disclaimerLines = doc.splitTextToSize(p.disclaimer, CONTENT_W - 20);
  const disclaimerH = disclaimerLines.length * 4.5 + 18;

  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(225, 220, 210);
  doc.setLineWidth(0.3);
  doc.roundedRect(MARGIN_L, disclaimerY, CONTENT_W, disclaimerH, 3, 3, "FD");

  doc.setFillColor(...DISCLAIMER_ICON_BG);
  doc.circle(MARGIN_L + 9, disclaimerY + 9, 4, "F");
  doc.setFont("Poppins", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...ORANGE);
  doc.text("i", MARGIN_L + 9, disclaimerY + 10.5, { align: "center" });

  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(9);
  doc.setTextColor(...NAVY);
  doc.setCharSpace(0.5);
  doc.text("IMPORTANT - PLEASE READ", MARGIN_L + 16, disclaimerY + 10);
  doc.setCharSpace(0);

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(60, 60, 60);
  doc.text(disclaimerLines, MARGIN_L + 6, disclaimerY + 18);

  const footerCoverY = PAGE_H - 22;
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(8);
  doc.setTextColor(...NAVY);
  doc.setCharSpace(0.8);
  doc.text("GENERATED BY BRAINWISE ENTERPRISES, LLC", MARGIN_L, footerCoverY);
  doc.setCharSpace(0);

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  const dateRight = new Date()
    .toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
    .toUpperCase();
  doc.text(dateRight, PAGE_W - MARGIN_R, footerCoverY, { align: "right" });

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(7);
  doc.setTextColor(140, 140, 140);
  const copyText = p.copyright.replace(/\{year\}/g, String(new Date().getFullYear()));
  const copyLines = doc.splitTextToSize(copyText, CONTENT_W);
  doc.text(copyLines, MARGIN_L, footerCoverY + 5);
}

export function stampPageNumbers(doc: jsPDF): void {
  const totalPages = doc.getNumberOfPages();
  const contentTotalPages = totalPages - 1;
  for (let p = 2; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(7);
    doc.setFont("Montserrat", "normal");
    doc.setTextColor(...MUTED);
    doc.text(
      `Page ${p - 1} of ${contentTotalPages}`,
      PAGE_W - MARGIN_R,
      FOOTER_Y,
      { align: "right" },
    );
  }
}

// ─── Distribution row helpers ───────────────────────────────────────────────

const ROW_LABEL_FONT = 8.5;
const ROW_LEFT_LABEL_W = 70;
const AXIS_LEFT_PAD = 2;
const AXIS_RIGHT_PAD = 2;

function drawAxis(
  ctx: PdfContext,
  axisY: number,
  axisX: number,
  axisW: number,
): void {
  const { doc } = ctx;
  doc.setDrawColor(210, 210, 210);
  doc.setLineWidth(0.2);
  doc.line(axisX, axisY, axisX + axisW, axisY);
  // 0/50/100 ticks
  doc.setDrawColor(220, 220, 220);
  [0, 50, 100].forEach((v) => {
    const x = axisX + (v / 100) * axisW;
    doc.line(x, axisY - 0.8, x, axisY + 0.8);
  });
}

export function drawPairDistRow(
  ctx: PdfContext,
  args: { label: string; a: number | null | undefined; b: number | null | undefined },
): void {
  const rowH = 10;
  ctx.checkPageBreak(rowH + 2);
  const { doc } = ctx;
  const y = ctx.y;
  const aVal = typeof args.a === "number" ? Math.max(0, Math.min(100, args.a)) : null;
  const bVal = typeof args.b === "number" ? Math.max(0, Math.min(100, args.b)) : null;

  // Label + gap on same line above axis
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(ROW_LABEL_FONT);
  doc.setTextColor(...NAVY);
  const labelLines = doc.splitTextToSize(cleanMarkdown(args.label), CONTENT_W - 30);
  doc.text(labelLines[0], MARGIN_L, y + 3);

  if (aVal != null && bVal != null) {
    const gap = Math.abs(aVal - bVal).toFixed(0);
    doc.setFont("Montserrat", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...MUTED);
    doc.text(`gap ${gap}`, MARGIN_L + CONTENT_W, y + 3, { align: "right" });
  }

  const axisY = y + 7.5;
  const axisX = MARGIN_L + AXIS_LEFT_PAD;
  const axisW = CONTENT_W - AXIS_LEFT_PAD - AXIS_RIGHT_PAD;
  drawAxis(ctx, axisY, axisX, axisW);

  if (aVal != null && bVal != null) {
    const ax = axisX + (aVal / 100) * axisW;
    const bx = axisX + (bVal / 100) * axisW;
    doc.setDrawColor(120, 120, 120);
    doc.setLineWidth(0.6);
    doc.line(Math.min(ax, bx), axisY, Math.max(ax, bx), axisY);
  }
  if (aVal != null) {
    const ax = axisX + (aVal / 100) * axisW;
    doc.setFillColor(...NAVY);
    doc.circle(ax, axisY, 1.6, "F");
  }
  if (bVal != null) {
    const bx = axisX + (bVal / 100) * axisW;
    doc.setFillColor(...MUSTARD);
    doc.circle(bx, axisY, 1.6, "F");
  }

  ctx.y = y + rowH + 1;
}

/** One recessive ink for every member dot. The shape bucket is already stated
 *  by the heading above the rows, so color carries no extra information here;
 *  a single mid-gray also clears the 3:1 contrast floor at 1.3mm. */
export const DIST_DOT: readonly [number, number, number] = [109, 104, 117];

/** Height of the compact strip drawn inside a driver card. */
export const DIST_STRIP_H = 9;

/**
 * The scale key for a run of distribution rows. Drawn once per section: the
 * axis ends and its midpoint, the member count, and the one direct label the
 * mean marker gets anywhere in the report.
 */
export function drawTeamDistScale(
  ctx: PdfContext,
  args: { n: number; x?: number; width?: number },
): void {
  const { doc } = ctx;
  const x = args.x ?? MARGIN_L;
  const w = args.width ?? CONTENT_W;
  ctx.checkPageBreak(16);
  const axisX = x + AXIS_LEFT_PAD;
  const axisW = w - AXIS_LEFT_PAD - AXIS_RIGHT_PAD;

  const keyY = ctx.y + 2;
  doc.setFont("Montserrat", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...MUTED);
  doc.text(`Each dot is one member's score (n=${args.n}).`, x, keyY);
  const lead = doc.getTextWidth(`Each dot is one member's score (n=${args.n}).`);
  const tickX = x + lead + 4;
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.9);
  doc.line(tickX, keyY - 2.4, tickX, keyY + 0.6);
  doc.setTextColor(...MUTED);
  doc.text("team mean", tickX + 2, keyY);

  const axisY = keyY + 5;
  drawAxis(ctx, axisY, axisX, axisW);
  doc.setFont("Montserrat", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...MUTED);
  doc.text("0", axisX, axisY + 3.4);
  doc.text("50", axisX + axisW / 2, axisY + 3.4, { align: "center" });
  doc.text("100", axisX + axisW, axisY + 3.4, { align: "right" });

  ctx.y = axisY + 6;
}

/** The dots + mean tick for one facet, at an explicit position. Returns the
 *  height consumed, so a card can measure it before drawing. */
export function drawDistStripAt(
  doc: jsPDF,
  args: { x: number; y: number; width: number; scores: number[] },
): number {
  const scores = (args.scores ?? []).filter((n) => typeof n === "number");
  if (scores.length === 0) return 0;
  const axisX = args.x + AXIS_LEFT_PAD;
  const axisW = args.width - AXIS_LEFT_PAD - AXIS_RIGHT_PAD;
  const axisY = args.y + DIST_STRIP_H / 2;

  doc.setDrawColor(210, 210, 210);
  doc.setLineWidth(0.2);
  doc.line(axisX, axisY, axisX + axisW, axisY);
  doc.setDrawColor(220, 220, 220);
  [0, 50, 100].forEach((v) => {
    const x = axisX + (v / 100) * axisW;
    doc.line(x, axisY - 0.8, x, axisY + 0.8);
  });

  const jitter = [-1.8, 0, 1.8];
  doc.setFillColor(DIST_DOT[0], DIST_DOT[1], DIST_DOT[2]);
  scores.forEach((s, i) => {
    const v = Math.max(0, Math.min(100, s));
    doc.circle(axisX + (v / 100) * axisW, axisY + jitter[i % 3], 1.3, "F");
  });

  const mean = scores.reduce((a, b) => a + b, 0) / scores.length;
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.9);
  const mx = axisX + (mean / 100) * axisW;
  doc.line(mx, axisY - 3, mx, axisY + 3);
  return DIST_STRIP_H;
}

export function drawTeamDistRow(
  ctx: PdfContext,
  args: { label: string; scores: number[] },
): void {
  const { doc } = ctx;
  const scores = Array.isArray(args.scores) ? args.scores.filter((n) => typeof n === "number") : [];

  if (scores.length === 0) {
    // Plain text row fallback
    const rowH = 6;
    ctx.checkPageBreak(rowH + 1);
    doc.setFont("Montserrat", "normal");
    doc.setFontSize(ROW_LABEL_FONT);
    doc.setTextColor(...BLACK);
    doc.text(cleanMarkdown(args.label), MARGIN_L, ctx.y + 4);
    ctx.y += rowH;
    return;
  }

  const rowH = 12;
  ctx.checkPageBreak(rowH + 2);
  const y = ctx.y;

  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(ROW_LABEL_FONT);
  doc.setTextColor(...NAVY);
  const labelLines = doc.splitTextToSize(cleanMarkdown(args.label), CONTENT_W - 30);
  doc.text(labelLines[0], MARGIN_L, y + 3);

  drawDistStripAt(doc, {
    x: MARGIN_L,
    y: y + 8 - DIST_STRIP_H / 2,
    width: CONTENT_W,
    scores,
  });

  ctx.y = y + rowH + 1;
}

/* ==========================================================================
   Bullet cards + facet chips — shared by the paired and team PDF generators.

   Extracted from generatePairedProfilePdf.ts, which was the superset (it is
   the only one that renders "THE MOVE" bullets; that path is simply inert for
   team, whose generator never emits a "The move:" prefix).

   Everything that genuinely differs between the two reports is a parameter:
   the facet label/color functions and the card metrics. No module-level
   mutable state lives here, so two concurrent generations cannot clobber each
   other's facet index.
   ========================================================================== */

/** Per-invocation facet styling. Built inside each generate call and threaded
 *  down, so no module-level mutable state is shared between renders. */
export interface FacetStyler {
  /** The label to print for a facet. Lookups keep using the raw name. */
  label: (name: string) => string;
  color: (name: string) => readonly [number, number, number];
  domain: (name: string) => string | undefined;
}

export const PDF_DIM_COLOR: Record<string, readonly [number, number, number]> = {
  Protection: NAVY,
  Participation: TEAL,
  Prediction: GRAY,
  Purpose: PURPLE,
  Pleasure: MUSTARD, // amber is illegible at chip sizes; mustard is its text-safe pair
};

/** Build a facet styler for one render. `mode` drives display labels only. */
export function makeFacetStyler(
  facets: { facetName?: string | null; domain?: string | null }[],
  mode: string | null,
): FacetStyler {
  const domainByName = new Map<string, string>();
  for (const f of facets) {
    const key = normFacetName(f?.facetName ?? "");
    if (key && f?.domain && !domainByName.has(key)) domainByName.set(key, f.domain);
  }
  const domain = (name: string) => domainByName.get(normFacetName(name));
  return {
    label: (name: string) => facetDisplayLabel(name, mode),
    color: (name: string) => {
      const dom = domain(name);
      return (dom && PDF_DIM_COLOR[dom]) || GRAY;
    },
    domain,
  };
}

/** jsPDF has no alpha on fills; blend toward white instead. */
export function tint(c: readonly [number, number, number], a: number): [number, number, number] {
  return [
    Math.round(255 + (c[0] - 255) * a),
    Math.round(255 + (c[1] - 255) * a),
    Math.round(255 + (c[2] - 255) * a),
  ];
}

export interface PdfBlock {
  /** bold lead sentence (object bullets only) */
  point?: string;
  text: string;
  facets?: string[];
  /** point began with "The move:" — green rule + THE MOVE label */
  move?: boolean;
}

/** Normalize a section value that may be a plain string (legacy reports) or an
 *  array of string / { point, body, facets } bullets. */
export function asBlocks(v: string | Bullet[] | undefined | null): PdfBlock[] {
  if (!v) return [];
  if (Array.isArray(v)) {
    return v
      .map((b) => {
        if (typeof b === "string" || !isBulletObject(b)) {
          return { text: bulletToText(b), facets: bulletFacets(b) } as PdfBlock;
        }
        const move = isMoveBullet(b);
        const point = move ? stripMovePrefix(b.point ?? "") : (b.point ?? "").trim();
        const body = (b.body ?? "").trim();
        return {
          point: point || undefined,
          text: point ? body : bulletToText(b),
          facets: bulletFacets(b),
          move,
        } as PdfBlock;
      })
      .filter((b) => !!(b.text || b.point));
  }
  return typeof v === "string" ? [{ text: v }] : [];
}

/* ---------- facet chips ---------- */

export const CHIP_H = 3.4;
export const CHIP_GAP_X = 1.5;
export const CHIP_GAP_Y = 1.2;
export const CHIP_PAD_X = 1.6;

export interface Chip {
  label: string;
  w: number;
  color: readonly [number, number, number];
}

export function chipLayout(
  doc: jsPDF,
  facets: string[] | undefined,
  maxW: number,
  fs: FacetStyler,
): { rows: Chip[][]; h: number } {
  const list = (facets ?? []).filter((f) => typeof f === "string" && f.trim());
  if (list.length === 0) return { rows: [], h: 0 };
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(6.5);
  const rows: Chip[][] = [];
  let row: Chip[] = [];
  let rowW = 0;
  for (const raw of list) {
    const label = fs.label(cleanMarkdown(raw).trim());
    if (!label) continue;
    const w = Math.min(maxW, doc.getTextWidth(label) + CHIP_PAD_X * 2 + 1.5);
    if (row.length > 0 && rowW + CHIP_GAP_X + w > maxW) {
      rows.push(row);
      row = [];
      rowW = 0;
    }
    row.push({ label, w, color: fs.color(raw) });
    rowW += (row.length > 1 ? CHIP_GAP_X : 0) + w;
  }
  if (row.length > 0) rows.push(row);
  const h = rows.length === 0 ? 0 : rows.length * CHIP_H + (rows.length - 1) * CHIP_GAP_Y;
  return { rows, h };
}

export function drawChipRows(doc: jsPDF, rows: Chip[][], x: number, top: number): void {
  let y = top;
  for (const row of rows) {
    let cx = x;
    for (const chip of row) {
      const fill = tint(chip.color, 0.1);
      const border = tint(chip.color, 0.3);
      doc.setFillColor(fill[0], fill[1], fill[2]);
      doc.setDrawColor(border[0], border[1], border[2]);
      doc.setLineWidth(0.2);
      doc.roundedRect(cx, y, chip.w, CHIP_H, CHIP_H / 2, CHIP_H / 2, "FD");
      doc.setFont("Montserrat", "semibold");
      doc.setFontSize(6.5);
      doc.setTextColor(chip.color[0], chip.color[1], chip.color[2]);
      doc.text(chip.label, cx + chip.w / 2, y + CHIP_H / 2 + 0.85, { align: "center" });
      cx += chip.w + CHIP_GAP_X;
    }
    y += CHIP_H + CHIP_GAP_Y;
  }
}

/* ---------- bullet cards ---------- */

export const CARD_PAD = 2.5;
export const CARD_GAP = 2;
export const CARD_RULE_W = 1.5;

/** Body type metrics differ per report and must not be flattened:
 *  paired is 8.5 / 4.1 / 4.4, team is 9 / 4.5 / 4.6. */
export interface CardMetrics {
  bodySize: number;
  lhBody: number;
  lhPoint: number;
}

export interface CardMeasure {
  h: number;
  pointLines: string[];
  textLines: string[];
  chips: { rows: Chip[][]; h: number };
  innerW: number;
  accent: readonly [number, number, number];
  move: boolean;
  metrics: CardMetrics;
}

export function measureCard(
  doc: jsPDF,
  b: PdfBlock,
  w: number,
  accent: readonly [number, number, number],
  fs: FacetStyler,
  metrics: CardMetrics,
): CardMeasure {
  const innerW = w - CARD_PAD * 2 - CARD_RULE_W;
  const move = !!b.move;
  doc.setFont("Poppins", "bold");
  doc.setFontSize(9.5);
  const pointLines: string[] = b.point
    ? doc.splitTextToSize(cleanMarkdown(b.point), innerW)
    : [];
  doc.setFont("Montserrat", "normal");
  doc.setFontSize(metrics.bodySize);
  const textLines: string[] = b.text ? doc.splitTextToSize(cleanMarkdown(b.text), innerW) : [];
  const chips = chipLayout(doc, b.facets, innerW, fs);
  const h =
    CARD_PAD * 2 +
    (move ? 3.2 : 0) +
    pointLines.length * metrics.lhPoint +
    textLines.length * metrics.lhBody +
    (chips.h > 0 ? chips.h + 0.8 : 0);
  return { h, pointLines, textLines, chips, innerW, accent: move ? GREEN : accent, move, metrics };
}

export function drawCardAt(
  doc: jsPDF,
  m: CardMeasure,
  x: number,
  y: number,
  w: number,
  framed = true,
): void {
  if (framed) {
    doc.setDrawColor(224, 222, 216);
    doc.setLineWidth(0.15);
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(x, y, w, m.h, 1.6, 1.6, "FD");
    doc.setFillColor(m.accent[0], m.accent[1], m.accent[2]);
    doc.rect(x, y, CARD_RULE_W, m.h, "F");
  }
  const tx = x + CARD_RULE_W + CARD_PAD;
  let cy = y + CARD_PAD + 2.6;
  if (m.move) {
    doc.setFont("Montserrat", "semibold");
    doc.setFontSize(6.5);
    doc.setTextColor(GREEN[0], GREEN[1], GREEN[2]);
    doc.text("THE MOVE", tx, cy, { charSpace: 0.5 });
    cy += 3.2;
  }
  if (m.pointLines.length > 0) {
    doc.setFont("Poppins", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...NAVY);
    for (const l of m.pointLines) {
      doc.text(l, tx, cy);
      cy += m.metrics.lhPoint;
    }
  }
  if (m.textLines.length > 0) {
    doc.setFont("Montserrat", "normal");
    doc.setFontSize(m.metrics.bodySize);
    doc.setTextColor(...BLACK);
    for (const l of m.textLines) {
      doc.text(l, tx, cy);
      cy += m.metrics.lhBody;
    }
  }
  if (m.chips.rows.length > 0) {
    drawChipRows(doc, m.chips.rows, tx, cy - 2.6 + 0.8);
  }
}

/** Accent rule color: the first facet's PTP dimension, else the section accent. */
export function blockAccent(
  b: PdfBlock,
  fallback: readonly [number, number, number],
  fs: FacetStyler,
): readonly [number, number, number] {
  for (const f of b.facets ?? []) {
    const dom = fs.domain(f);
    if (dom && PDF_DIM_COLOR[dom]) return PDF_DIM_COLOR[dom];
  }
  return fallback;
}
