import jsPDF from "jspdf";

const NAVY: [number, number, number] = [2, 31, 54];
const ORANGE: [number, number, number] = [245, 116, 26];
const MUTED: [number, number, number] = [109, 104, 117];
const BLACK: [number, number, number] = [30, 30, 30];
const SAND_BG: [number, number, number] = [249, 247, 241];

interface Block { heading: string; items: string[] }
interface Section { label?: string; snapshot: string; blocks: Block[] }
export interface OnePager {
  audience: "work" | "therapist" | "partner" | "friend";
  title: string;
  disclaimer?: string;
  sections: Section[];
  nutshell: string;
}

export async function generateOnePagerPdf(
  onePager: OnePager,
  opts: { userName: string; dateTaken?: string }
): Promise<void> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const { registerPdfFonts } = await import("./pdfFonts");
  await registerPdfFonts(doc);

  const PAGE_W = doc.internal.pageSize.getWidth();
  const PAGE_H = doc.internal.pageSize.getHeight();
  const M = 16;
  const CONTENT_W = PAGE_W - M * 2;
  let y = M;

  const logo = await (async () => {
    try {
      const res = await fetch("/logo-orange-white.png");
      if (!res.ok) return null;
      const blob = await res.blob();
      return await new Promise<string>((resolve) => {
        const r = new FileReader();
        r.onloadend = () => resolve(r.result as string);
        r.readAsDataURL(blob);
      });
    } catch {
      return null;
    }
  })();

  const BAND_H = 32;
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, PAGE_W, BAND_H, "F");
  if (logo) {
    doc.addImage(logo, "PNG", M, 8, 34, 0, undefined, "FAST");
  } else {
    doc.setFont("Poppins", "extrabold");
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.text("BrainWise", M, 20);
  }
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(9);
  doc.setTextColor(...ORANGE);
  doc.setCharSpace(1);
  doc.text("ONE-PAGE SNAPSHOT", PAGE_W - M, 18, { align: "right" });
  doc.setCharSpace(0);
  y = BAND_H + 10;

  doc.setFont("Poppins", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...NAVY);
  const tl = doc.splitTextToSize(onePager.title, CONTENT_W);
  doc.text(tl, M, y);
  y += tl.length * 7 + 2;

  if (onePager.disclaimer) {
    doc.setFont("Montserrat", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    const dl = doc.splitTextToSize(onePager.disclaimer, CONTENT_W);
    doc.text(dl, M, y);
    y += dl.length * 4 + 3;
  }

  const ensure = (h: number) => {
    if (y + h > PAGE_H - 16) {
      doc.addPage();
      y = M;
    }
  };

  for (const s of onePager.sections) {
    if (s.label) {
      ensure(10);
      doc.setFont("Poppins", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...ORANGE);
      doc.text(s.label.toUpperCase(), M, y);
      y += 6;
    }
    doc.setFont("Montserrat", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(...BLACK);
    const snap = doc.splitTextToSize(s.snapshot, CONTENT_W);
    ensure(snap.length * 4.6 + 4);
    doc.text(snap, M, y);
    y += snap.length * 4.6 + 3;
    for (const b of s.blocks) {
      ensure(8);
      doc.setFont("Poppins", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...NAVY);
      doc.text(b.heading, M, y);
      y += 5;
      doc.setFont("Montserrat", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...BLACK);
      for (const it of b.items) {
        const lines = doc.splitTextToSize(it, CONTENT_W - 5);
        ensure(lines.length * 4.4 + 1);
        doc.text("•", M, y);
        doc.text(lines, M + 4, y);
        y += lines.length * 4.4 + 1.5;
      }
      y += 1.5;
    }
    y += 3;
  }

  ensure(16);
  const nut = doc.splitTextToSize("In a nutshell: " + onePager.nutshell, CONTENT_W - 8);
  const nutH = nut.length * 4.6 + 8;
  doc.setFillColor(...SAND_BG);
  doc.roundedRect(M, y, CONTENT_W, nutH, 2, 2, "F");
  doc.setFont("Montserrat", "semibold");
  doc.setFontSize(9.5);
  doc.setTextColor(...NAVY);
  doc.text(nut, M + 4, y + 6);
  y += nutH + 4;

  doc.setFont("Montserrat", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text(
    `${opts.userName} · Generated by BrainWise${opts.dateTaken ? " · " + opts.dateTaken : ""} · Confidential`,
    M,
    PAGE_H - 8
  );

  doc.save(`${opts.userName.replace(/\s+/g, "_")}_${onePager.audience}_one-page-snapshot.pdf`);
}
