/**
 * Map of PTP item numbers (1–89) to their canonical facet names.
 * Each name carries its context label: (professional) or (personal).
 * Shared between the PTPFullFacetCharts UI component, PTPNarrativeSections,
 * and the PDF data assembler.
 */
export const PTP_ITEM_FACET_NAMES: Record<number, string> = {
  1: "Physical safety orientation (professional)",
  2: "Emotional safety (professional)",
  3: "Financial security orientation (professional)",
  4: "Short-term loss aversion (professional)",
  5: "Status and standing vigilance (professional)",
  6: "Personal fairness sensitivity (professional)",
  7: "Equality and reciprocity need (professional)",
  8: "Resilience and recovery capacity (professional)",
  9: "Physical health vigilance (professional)",
  10: "Need to be trusted (professional)",
  11: "Need to trust others (professional)",
  12: "Similarity-based affiliation (professional)",
  13: "Group belonging need (professional)",
  14: "Need for individual differentiation (professional)",
  15: "Contrarian opinion drive (professional)",
  16: "Team orientation (professional)",
  17: "Self-esteem and self-respect (professional)",
  18: "Social comparison drive (professional)",
  19: "Recognition need (professional)",
  20: "Approval and respect need (professional)",
  21: "Power and influence need (professional)",
  22: "Status and prestige need (professional)",
  23: "Embarrassment avoidance (professional)",
  24: "Impostor sensitivity (professional)",
  25: "Future certainty need (professional)",
  26: "Expectation clarity need (professional)",
  27: "Evaluation criteria need (professional)",
  28: "Reward predictability need (professional)",
  29: "Autonomy and control need (professional)",
  30: "Action orientation (professional)",
  31: "Information and situational awareness (professional)",
  32: "Correctness need (professional)",
  33: "Perfectionism (professional)",
  34: "Status quo and stability need (professional)",
  35: "Sense-making need (professional)",
  36: "Consistency need (professional)",
  37: "Ambiguity intolerance (professional)",
  38: "Surprise aversion (professional)",
  39: "Conformity need (professional)",
  40: "Doubt intolerance (professional)",
  41: "Authenticity need (professional)",
  42: "Risk aversion (professional)",
  43: "Curiosity (professional)",
  44: "Voice and influence need (professional)",
  45: "Need for structure (professional)",
  46: "Commitment reliability need (professional)",
  47: "Well-being vigilance for close others (professional)",
  48: "Emotional safety (personal)",
  49: "Financial loss aversion (personal)",
  50: "Environmental safety scanning (personal)",
  51: "Other-directed fairness sensitivity (personal)",
  52: "Animal welfare sensitivity (personal)",
  53: "Social equality vigilance (personal)",
  54: "Mental health vigilance (personal)",
  55: "Emotional health vigilance (personal)",
  56: "Spiritual health vigilance (personal)",
  57: "Power and influence need (personal)",
  58: "Status and prestige need (personal)",
  59: "Benevolence drive (personal)",
  60: "Future certainty need (personal)",
  61: "Expectation clarity need (personal)",
  62: "Autonomy and control need (personal)",
  63: "Action orientation (personal)",
  64: "Status quo and stability need (personal)",
  65: "Sense-making need (personal)",
  66: "Ambiguity intolerance (personal)",
  67: "Surprise aversion (personal)",
  68: "Risk aversion (personal)",
  69: "Self-directed independence need (personal)",
  70: "Tradition and ritual orientation (personal)",
  71: "Harmony and stability need (personal)",
  72: "Need for structure (personal)",
  73: "Commitment reliability need (personal)",
  74: "Mastery and craft orientation (personal)",
  75: "Self-development drive (personal)",
  76: "Mission and meaning orientation (personal)",
  77: "Values alignment (personal)",
  78: "Values alignment (organisational) (personal)",
  79: "Artistic and creative expression (personal)",
  80: "Spiritual orientation (personal)",
  81: "Passionate pursuit orientation (personal)",
  82: "Challenge and growth orientation (personal)",
  83: "Truth-seeking orientation (personal)",
  84: "Happiness pursuit (personal)",
  85: "Sensory and sensual gratification (personal)",
  86: "Instant gratification orientation (personal)",
  87: "Stimulation and excitement need (personal)",
  88: "Play orientation (personal)",
  89: "Love and attachment need (personal)",
};
