/**
 * Map of PTP item numbers (1–89) to their canonical facet names.
 * Shared between the PTPFullFacetCharts UI component and the PDF data assembler.
 */
export const PTP_ITEM_FACET_NAMES: Record<number, string> = {
  1: "Physical safety orientation",
  2: "Emotional safety (professional)",
  3: "Financial security orientation",
  4: "Short-term loss aversion",
  5: "Status and standing vigilance",
  6: "Personal fairness sensitivity",
  7: "Equality and reciprocity need",
  8: "Resilience and recovery capacity",
  9: "Physical health vigilance",
  10: "Need to be trusted",
  11: "Need to trust others",
  12: "Similarity-based affiliation",
  13: "Group belonging need",
  14: "Need for individual differentiation",
  15: "Contrarian opinion drive",
  16: "Team orientation",
  17: "Self-esteem and self-respect",
  18: "Social comparison drive",
  19: "Recognition need",
  20: "Approval and respect need",
  21: "Power and influence need (professional)",
  22: "Status and prestige need (professional)",
  23: "Embarrassment avoidance",
  24: "Impostor sensitivity",
  25: "Future certainty need (professional)",
  26: "Expectation clarity need (professional)",
  27: "Evaluation criteria need",
  28: "Reward predictability need",
  29: "Autonomy and control need (professional)",
  30: "Action orientation (professional)",
  31: "Information and situational awareness",
  32: "Correctness need",
  33: "Perfectionism",
  34: "Status quo and stability need (professional)",
  35: "Sense-making need (professional)",
  36: "Consistency need",
  37: "Ambiguity tolerance (professional)",
  38: "Surprise aversion (professional)",
  39: "Conformity need",
  40: "Doubt tolerance",
  41: "Authenticity need",
  42: "Risk tolerance (professional)",
  43: "Curiosity",
  44: "Voice and influence need",
  45: "Flexibility and flow capacity (professional)",
  46: "Commitment reliability need (professional)",
  47: "Well-being vigilance for close others",
  48: "Emotional safety (personal)",
  49: "Financial loss aversion",
  50: "Environmental safety scanning",
  51: "Other-directed fairness sensitivity",
  52: "Animal welfare sensitivity",
  53: "Social equality vigilance",
  54: "Mental health vigilance",
  55: "Emotional health vigilance",
  56: "Spiritual health vigilance",
  57: "Power and influence need (personal)",
  58: "Status and prestige need (personal)",
  59: "Benevolence drive",
  60: "Future certainty need (personal)",
  61: "Expectation clarity need (personal)",
  62: "Autonomy and control need (personal)",
  63: "Action orientation (personal)",
  64: "Status quo and stability need (personal)",
  65: "Sense-making need (personal)",
  66: "Ambiguity tolerance (personal)",
  67: "Surprise aversion (personal)",
  68: "Risk tolerance (personal)",
  69: "Self-directed independence need",
  70: "Tradition and ritual orientation",
  71: "Harmony and stability need",
  72: "Flexibility and flow capacity (personal)",
  73: "Commitment reliability need (personal)",
  74: "Mastery and craft orientation",
  75: "Self-development drive",
  76: "Mission and meaning orientation",
  77: "Values alignment (personal)",
  78: "Values alignment (organisational)",
  79: "Artistic and creative expression",
  80: "Spiritual orientation",
  81: "Passionate pursuit orientation",
  82: "Challenge and growth orientation",
  83: "Truth-seeking orientation",
  84: "Happiness pursuit",
  85: "Sensory and sensual gratification",
  86: "Instant gratification orientation",
  87: "Stimulation and excitement need",
  88: "Play orientation",
  89: "Love and attachment need",
};
